from __future__ import annotations

from typing import Any, Dict, List


AI_SCHEDULE_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "daily_horoscope",
        "title": "Ежедневные гороскопы",
        "description": "Старт в 08:00, затем каждые 10 минут (с дневным лимитом 12).",
        "schedule_kind": "cron",
        "scheduled_time": None,
        "cron_expression": "*/10 8-23 * * *",
        "posting_frequency": "daily",
        "articles_per_run": 1,
        "interval_minutes": None,
        "weekday": None,
        "max_runs": None,
        "tags": "гороскопы, прогнозы",
        "payload_template": {
            "publish_mode": "published",
            "generate_image": True,
            "include_push": False,
            "daily_limit": 12,
            "target_date_offset": 1,
            "disable_faq": True,
        },
    },
    {
        "id": "articles_14_per_day",
        "title": "Статьи: 14 в день",
        "description": "1 статья каждый час с 08:00 до 21:00 (14 публикаций/сутки).",
        "schedule_kind": "cron",
        "scheduled_time": None,
        "cron_expression": "0 8-21 * * *",
        "posting_frequency": "daily",
        "articles_per_run": 1,
        "interval_minutes": None,
        "weekday": None,
        "max_runs": None,
        "tags": "автопостинг, статьи, контент",
        "payload_template": {
            "publish_mode": "published",
            "daily_limit": 14,
            "disable_faq": False,
        },
    },
    {
        "id": "articles_2_per_day",
        "title": "Статьи: 2 в день",
        "description": "Сбалансированный режим: публикации в 10:00 и 18:00.",
        "schedule_kind": "cron",
        "scheduled_time": None,
        "cron_expression": "0 10,18 * * *",
        "posting_frequency": "daily",
        "articles_per_run": 1,
        "interval_minutes": None,
        "weekday": None,
        "max_runs": None,
        "tags": "категории, статьи, стабильный-поток",
        "payload_template": {
            "publish_mode": "draft",
            "daily_limit": 2,
            "disable_faq": False,
        },
    },
    {
        "id": "nightly_seo_refresh",
        "title": "Ночная SEO‑переиндексация",
        "description": "Запуск SEO‑пайплайна для опубликованных статей каждую ночь.",
        "schedule_kind": "cron",
        "scheduled_time": None,
        "cron_expression": "0 3 * * *",
        "posting_frequency": "daily",
        "articles_per_run": 4,
        "interval_minutes": None,
        "weekday": None,
        "max_runs": None,
        "tags": "seo, оптимизация",
        "payload_template": {
            "mode": "nightly-refresh",
            "max_posts": 4,
        },
    },
    {
        "id": "distribution_followup",
        "title": "Дистрибуция статей по соцсетям",
        "description": "Каждый час запускает пайплайн рассылки свежих постов.",
        "schedule_kind": "interval",
        "scheduled_time": None,
        "cron_expression": "",
        "posting_frequency": "daily",
        "articles_per_run": 3,
        "interval_minutes": 60,
        "weekday": None,
        "max_runs": None,
        "tags": "smm, рассылка",
        "payload_template": {
            "channels": ["telegram", "vk", "dzen"],
            "min_post_age_minutes": 30,
        },
    },
]

