# Generated by Django 5.0.8 on 2025-12-03 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной профиль', max_length=200, verbose_name='Название профиля')),
                ('is_active', models.BooleanField(default=True, help_text='Будет использоваться для проверки статей', verbose_name='Активен')),
                ('check_title', models.BooleanField(default=True, help_text='Заголовок не должен быть пустым', verbose_name='Проверять заголовок')),
                ('check_image', models.BooleanField(default=True, help_text='Статья должна содержать изображение', verbose_name='Проверять наличие изображения')),
                ('check_category', models.BooleanField(default=True, help_text='У статьи должна быть выбрана категория', verbose_name='Проверять категорию')),
                ('check_length', models.BooleanField(default=True, help_text='Проверять минимальное количество слов', verbose_name='Проверять длину текста')),
                ('check_profanity', models.BooleanField(default=False, help_text='Простая проверка на наличие матерных слов', verbose_name='Проверять мат')),
                ('min_words', models.IntegerField(default=300, help_text='Минимальное количество слов в статье', verbose_name='Минимум слов')),
                ('min_title_length', models.IntegerField(default=10, help_text='Минимальная длина заголовка', verbose_name='Минимум символов в заголовке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': '📝 Модерация: Настройки статей',
                'verbose_name_plural': '📝 Модерация: Настройки статей',
                'db_table': 'asistent_articlemoderationsettings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной профиль', max_length=200, verbose_name='Название профиля')),
                ('is_active', models.BooleanField(default=True, help_text='Будет использоваться для проверки комментариев', verbose_name='Активен')),
                ('block_urls', models.BooleanField(default=True, help_text='Запретить комментарии с http://, https://, www.', verbose_name='Блокировать ссылки')),
                ('block_html', models.BooleanField(default=True, help_text='Запретить комментарии с HTML-разметкой', verbose_name='Блокировать HTML-теги')),
                ('block_short', models.BooleanField(default=True, help_text='Запретить слишком короткие комментарии', verbose_name='Блокировать короткие')),
                ('check_spam', models.BooleanField(default=True, help_text='Простая проверка спам-слов', verbose_name='Проверять на спам')),
                ('min_length', models.IntegerField(default=10, help_text='Минимальная длина комментария', verbose_name='Минимум символов')),
                ('forbidden_words', models.TextField(blank=True, help_text='Список через запятую: купить, казино, спам, реклама', verbose_name='Запрещённые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': '💬 Модерация: Настройки комментариев',
                'verbose_name_plural': '💬 Модерация: Настройки комментариев',
                'db_table': 'asistent_commentmoderationsettings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Статья'), ('comment', 'Комментарий')], default='article', max_length=20, verbose_name='Тип контента')),
                ('object_id', models.IntegerField(default=0, help_text='ID статьи или комментария', verbose_name='ID объекта')),
                ('passed', models.BooleanField(default=False, help_text='True = пройдена, False = отклонена', verbose_name='Пройдена')),
                ('problems', models.TextField(blank=True, help_text='Причины отклонения (по одной на строке)', verbose_name='Список проблем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('moderator', models.ForeignKey(blank=True, help_text='Кто выполнил проверку (NULL = автомат)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': '📋 Модерация: Журнал проверок',
                'verbose_name_plural': '📋 Модерация: Журнал проверок',
                'db_table': 'asistent_moderationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='asistent_mo_created_145bd7_idx'), models.Index(fields=['content_type', 'object_id'], name='asistent_mo_content_3ba63a_idx'), models.Index(fields=['passed'], name='asistent_mo_passed_34fb98_idx')],
            },
        ),
    ]
