# Generated by Django 5.0.8 on 2025-12-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0001_initial'),
        ('blog', '0029_add_og_preview_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRegeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regenerated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регенерации')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('regeneration_notes', models.TextField(blank=True, help_text='Дополнительная информация о процессе регенерации', verbose_name='Заметки о регенерации')),
                ('original_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regenerations', to='blog.post', verbose_name='Оригинальная статья')),
                ('regenerated_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerated_from', to='blog.post', verbose_name='Регенерированная статья')),
            ],
            options={
                'verbose_name': '🔄 Регенерация статей',
                'verbose_name_plural': '🔄 Регенерация статей',
                'db_table': 'asistent_articleregeneration',
                'ordering': ['-regenerated_at'],
                'indexes': [models.Index(fields=['-regenerated_at'], name='asistent_ar_regener_07ba2b_idx'), models.Index(fields=['status'], name='asistent_ar_status_88b507_idx'), models.Index(fields=['original_article'], name='asistent_ar_origina_936e16_idx')],
            },
        ),
    ]
