# Generated by Django 5.1 on 2025-10-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='external_code',
            field=models.TextField(blank=True, help_text='Код от Google AdSense, Яндекс.Директ и других сетей', verbose_name='Внешний код рекламы'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='use_external_code',
            field=models.BooleanField(default=False, help_text='Если True, будет показан external_code вместо image/video', verbose_name='Использовать внешний код'),
        ),
        migrations.CreateModel(
            name='AdActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('activate', 'Активация'), ('deactivate', 'Деактивация'), ('insert', 'Вставка в статью'), ('remove', 'Удаление из статьи')], max_length=20, verbose_name='Тип действия')),
                ('performed_by_ai', models.BooleanField(default=False, help_text='True если действие выполнено AI-агентом', verbose_name='Выполнено AI')),
                ('target_type', models.CharField(help_text='banner, context_ad, insertion, campaign и т.д.', max_length=50, verbose_name='Тип объекта')),
                ('target_id', models.IntegerField(verbose_name='ID объекта')),
                ('target_name', models.CharField(blank=True, help_text='Для удобства отображения', max_length=255, verbose_name='Название объекта')),
                ('old_data', models.JSONField(blank=True, help_text='JSON со старыми значениями полей', null=True, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, help_text='JSON с новыми значениями полей', null=True, verbose_name='Новые данные')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('can_revert', models.BooleanField(default=True, help_text='True если действие можно отменить', verbose_name='Можно отменить')),
                ('reverted', models.BooleanField(default=False, verbose_name='Отменено')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Пользователь, выполнивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_ad_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
            ],
            options={
                'verbose_name': 'Действие с рекламой',
                'verbose_name_plural': 'Журнал действий с рекламой',
                'db_table': 'advertising_action_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='advertising_timesta_98b0ef_idx'), models.Index(fields=['target_type', 'target_id'], name='advertising_target__934395_idx'), models.Index(fields=['performed_by_ai', '-timestamp'], name='advertising_perform_960cd4_idx')],
            },
        ),
    ]
