# Generated by Django 5.1 on 2025-10-22 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_adbanner_external_code_adbanner_use_external_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название скрипта для внутреннего использования', max_length=200, verbose_name='Название')),
                ('script_type', models.CharField(choices=[('analytics', 'Аналитика/Счетчик'), ('advertising', 'Реклама'), ('pixel', 'Пиксель отслеживания'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип скрипта')),
                ('code', models.TextField(help_text='Полный HTML/JavaScript код для вставки', verbose_name='Код скрипта')),
                ('position', models.CharField(choices=[('head_start', 'Начало <head>'), ('head_end', 'Конец <head>'), ('body_start', 'Начало <body>'), ('body_end', 'Конец <body>')], default='head_end', max_length=20, verbose_name='Позиция на странице')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить скрипт на сайте', verbose_name='Активен')),
                ('priority', models.IntegerField(default=10, help_text='Порядок загрузки (меньше = раньше)', verbose_name='Приоритет')),
                ('description', models.TextField(blank=True, help_text='Для чего этот скрипт', verbose_name='Описание')),
                ('provider', models.CharField(blank=True, help_text='Название сервиса (например, ACINT, Google Analytics)', max_length=100, verbose_name='Провайдер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Внешний скрипт',
                'verbose_name_plural': 'Внешние скрипты',
                'db_table': 'advertising_external_script',
                'ordering': ['position', 'priority', '-created_at'],
            },
        ),
    ]
