# Generated by Django 5.1 on 2025-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_externalscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='unlimited_impressions',
            field=models.BooleanField(default=True, help_text='Если включено, баннер будет показываться без ограничений по количеству показов и времени. Расписание можно не заполнять. При снятии галочки вступает в силу расписание (если заполнено) или безлимитное отображение по умолчанию', verbose_name='Безлимитное отображение'),
        ),
    ]
