# Generated by Django 5.1 on 2025-10-23 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_adbanner_unlimited_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='banner_height',
            field=models.IntegerField(default=100, help_text='Высота отображения баннера в пикселях (от 50 до 300)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='Высота баннера (px)'),
        ),
    ]
