# Generated by Django 5.1 on 2025-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_adbanner_banner_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='card1_icon',
            field=models.CharField(blank=True, default='📸', max_length=10, verbose_name='Иконка карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card1_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Изображение карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card1_text',
            field=models.CharField(blank=True, default='Карточка 1', max_length=200, verbose_name='Текст карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card1_title',
            field=models.CharField(blank=True, default='Изображение', max_length=100, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card1_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео'), ('text', 'Текст')], default='text', max_length=20, verbose_name='Тип карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card1_video',
            field=models.FileField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Видео карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_icon',
            field=models.CharField(blank=True, default='🎥', max_length=10, verbose_name='Иконка карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Изображение карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_text',
            field=models.CharField(blank=True, default='Карточка 2', max_length=200, verbose_name='Текст карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_title',
            field=models.CharField(blank=True, default='Видео', max_length=100, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео'), ('text', 'Текст')], default='text', max_length=20, verbose_name='Тип карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_video',
            field=models.FileField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Видео карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_icon',
            field=models.CharField(blank=True, default='🎨', max_length=10, verbose_name='Иконка карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Изображение карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_text',
            field=models.CharField(blank=True, default='Карточка 3', max_length=200, verbose_name='Текст карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_title',
            field=models.CharField(blank=True, default='Дизайн', max_length=100, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео'), ('text', 'Текст')], default='text', max_length=20, verbose_name='Тип карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_video',
            field=models.FileField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Видео карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_icon',
            field=models.CharField(blank=True, default='✨', max_length=10, verbose_name='Иконка карточки 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Изображение карточки 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_text',
            field=models.CharField(blank=True, default='Карточка 4', max_length=200, verbose_name='Текст карточки 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_title',
            field=models.CharField(blank=True, default='Стиль', max_length=100, verbose_name='Заголовок карточки 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео'), ('text', 'Текст')], default='text', max_length=20, verbose_name='Тип карточки 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_video',
            field=models.FileField(blank=True, null=True, upload_to='advertising/cards/', verbose_name='Видео карточки 4'),
        ),
    ]
