# Generated by Django 5.1 on 2025-10-27 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_adbanner_card1_icon_adbanner_card1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplace',
            name='popup_cookie_hours',
            field=models.IntegerField(default=24, help_text='Как долго не показывать popup после закрытия в стандартном режиме (1-168 часов = 1-7 дней)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='🍪 Cookie на сколько часов'),
        ),
        migrations.AddField(
            model_name='adplace',
            name='popup_delay_seconds',
            field=models.IntegerField(default=5, help_text='Через сколько секунд после загрузки страницы показать popup (0-60 сек)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='⏱️ Задержка первого всплывания (сек)'),
        ),
        migrations.AddField(
            model_name='adplace',
            name='popup_test_interval_seconds',
            field=models.IntegerField(default=15, help_text='Каждые сколько секунд всплывает popup в тестовом режиме (5-300 сек)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Интервал в тестовом режиме (сек)'),
        ),
        migrations.AddField(
            model_name='adplace',
            name='popup_test_mode',
            field=models.BooleanField(default=False, help_text='Если включено: popup всплывает каждые N секунд (для тестирования). Если выключено: стандартный режим с cookie', verbose_name='🧪 Тестовый режим popup'),
        ),
    ]
