# Generated by Django 5.1 on 2025-10-27 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_add_popup_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='card1_text_overlay',
            field=models.JSONField(blank=True, default=dict, help_text='{"text": "Текст", "color": "#ffffff", "size": 24, "x": 50, "y": 50}', verbose_name='Текст поверх изображения/видео 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_text_overlay',
            field=models.JSONField(blank=True, default=dict, help_text='{"text": "Текст", "color": "#ffffff", "size": 24, "x": 50, "y": 50}', verbose_name='Текст поверх изображения/видео 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_text_overlay',
            field=models.JSONField(blank=True, default=dict, help_text='{"text": "Текст", "color": "#ffffff", "size": 24, "x": 50, "y": 50}', verbose_name='Текст поверх изображения/видео 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_text_overlay',
            field=models.JSONField(blank=True, default=dict, help_text='{"text": "Текст", "color": "#ffffff", "size": 24, "x": 50, "y": 50}', verbose_name='Текст поверх изображения/видео 4'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='main_text_overlay',
            field=models.JSONField(blank=True, default=dict, help_text='{"text": "Текст", "color": "#ffffff", "size": 32, "x": 50, "y": 50, "align": "center"}', verbose_name='Текст поверх основного изображения/видео'),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='banner_height',
            field=models.IntegerField(default=100, help_text='Высота отображения баннера в пикселях (от 50 до 500)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Высота баннера (px)'),
        ),
    ]
