# Generated by Django 5.0.8 on 2025-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0008_add_text_overlay_and_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='card1_url',
            field=models.URLField(blank=True, help_text='Если не указана, используется общая ссылка баннера', null=True, verbose_name='Ссылка карточки 1'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card2_url',
            field=models.URLField(blank=True, help_text='Если не указана, используется общая ссылка баннера', null=True, verbose_name='Ссылка карточки 2'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card3_url',
            field=models.URLField(blank=True, help_text='Если не указана, используется общая ссылка баннера', null=True, verbose_name='Ссылка карточки 3'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='card4_url',
            field=models.URLField(blank=True, help_text='Если не указана, используется общая ссылка баннера', null=True, verbose_name='Ссылка карточки 4'),
        ),
    ]
