# Generated by Django 5.0.8 on 2025-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_add_card_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsTxtSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='idealimage.ru', help_text='Домен сайта для ads.txt', max_length=200, verbose_name='Домен')),
                ('ezoic_manager_url', models.URLField(default='https://srv.adstxtmanager.com/19390/idealimage.ru', help_text='URL для получения ads.txt от Ezoic', max_length=500, verbose_name='URL менеджера Ezoic')),
                ('content', models.TextField(blank=True, help_text='Текущее содержимое файла ads.txt', verbose_name='Содержимое ads.txt')),
                ('auto_update', models.BooleanField(default=True, help_text='Автоматически обновлять файл от Ezoic', verbose_name='Автоматическое обновление')),
                ('update_interval_hours', models.IntegerField(default=24, help_text='Как часто обновлять файл (в часах)', verbose_name='Интервал обновления (часы)')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить ads.txt', verbose_name='Активен')),
                ('last_update_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка обновления')),
                ('last_successful_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее успешное обновление')),
                ('last_error', models.TextField(blank=True, help_text='Текст последней ошибки при обновлении', verbose_name='Последняя ошибка')),
                ('update_count', models.IntegerField(default=0, help_text='Счётчик успешных обновлений', verbose_name='Количество обновлений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки ads.txt',
                'verbose_name_plural': 'Настройки ads.txt',
                'db_table': 'advertising_ads_txt_settings',
            },
        ),
    ]
