# Generated by Django 5.2.7 on 2025-10-09 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0014_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора критериев')),
                ('criteria', models.JSONField(default=dict, help_text='JSON с критериями: min_length, max_length, required_keywords, forbidden_words, tone, structure, etc.', verbose_name='Критерии проверки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Критерий модерации',
                'verbose_name_plural': 'Критерии модерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название расписания')),
                ('source_urls', models.TextField(help_text='Сайты для мониторинга новостей', verbose_name='URL источников (по одному на строке)')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)')),
                ('posting_frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели'), ('monthly', 'Ежемесячно')], default='daily', max_length=20, verbose_name='Частота публикаций')),
                ('articles_per_run', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Статей за раз')),
                ('min_word_count', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Минимум слов в статье')),
                ('max_word_count', models.IntegerField(default=1500, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Максимум слов в статье')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые фразы для включения')),
                ('tone', models.CharField(default='дружелюбный и экспертный', max_length=200, verbose_name='Тон статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория для публикации')),
            ],
            options={
                'verbose_name': 'Расписание AI',
                'verbose_name_plural': 'Расписания AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_urls', models.TextField(help_text='URL источников, использованных для генерации', verbose_name='Источники')),
                ('prompt', models.TextField(help_text='Промпт, отправленный в AI', verbose_name='Промпт')),
                ('ai_response', models.TextField(verbose_name='Ответ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_info', to='blog.post', verbose_name='Статья')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_articles', to='Asistent.aischedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'AI-статья',
                'verbose_name_plural': 'AI-статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('required_word_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Минимальное количество слов')),
                ('required_links', models.TextField(blank=True, verbose_name='Обязательные ссылки (по одной на строке)')),
                ('required_keywords', models.TextField(blank=True, verbose_name='Ключевые фразы (по одной на строке)')),
                ('reward', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Вознаграждение (руб.)')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('taken', 'Взято в работу'), ('submitted', 'Отправлено на проверку'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='available', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='blog.post', verbose_name='Статья')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_available', 'Новое задание'), ('task_taken', 'Задание взято'), ('moderation_passed', 'Модерация пройдена'), ('moderation_failed', 'Модерация не пройдена'), ('task_approved', 'Задание одобрено'), ('task_rejected', 'Задание отклонено'), ('payment', 'Начисление средств'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='blog.post', verbose_name='Связанная статья')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Asistent.contenttask', verbose_name='Связанное задание')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('task_completed', 'Выполнение задания'), ('donation', 'Донат'), ('bonus', 'Бонус'), ('penalty', 'Штраф'), ('withdrawal', 'Вывод средств')], max_length=20, verbose_name='Тип транзакции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Asistent.contenttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('error', 'Ошибка')], max_length=20, verbose_name='Вердикт')),
                ('notes', models.TextField(blank=True, verbose_name='Замечания AI')),
                ('ai_response', models.JSONField(default=dict, verbose_name='Полный ответ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='blog.post', verbose_name='Статья')),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asistent.moderationcriteria', verbose_name='Критерии')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(verbose_name='Дата выполнения')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вознаграждение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks_history', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Asistent.contenttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'История задания',
                'verbose_name_plural': 'История заданий',
                'ordering': ['-completed_at'],
            },
        ),
    ]
