# Generated by Django 5.2.7 on 2025-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора критериев')),
                ('action', models.CharField(choices=[('delete', 'Удалить комментарий'), ('correct', 'Корректировать комментарий'), ('reply', 'Написать ответ автоматически')], default='delete', max_length=20, verbose_name='Действие при нарушении')),
                ('criteria', models.JSONField(default=dict, help_text='JSON с критериями: forbidden_words, min_length, max_length, spam_patterns, tone_rules, etc.', verbose_name='Критерии проверки')),
                ('reply_template', models.TextField(blank=True, help_text="Используется только для действия 'Написать ответ'. Переменные: {author}, {comment}, {reason}", verbose_name='Шаблон ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Критерий модерации комментариев',
                'verbose_name_plural': 'Критерии модерации комментариев',
                'ordering': ['-created_at'],
            },
        ),
    ]
