# Generated by Django 5.2.7 on 2025-10-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0002_commentmoderationcriteria'),
        ('blog', '0016_alter_like_unique_together_like_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('deleted', 'Удалён'), ('corrected', 'Откорректирован'), ('replied', 'Дан ответ')], max_length=20, verbose_name='Выполненное действие')),
                ('original_text', models.TextField(verbose_name='Оригинальный текст')),
                ('corrected_text', models.TextField(blank=True, verbose_name='Исправленный текст')),
                ('reason', models.TextField(verbose_name='Причина модерации')),
                ('reply_comment_id', models.IntegerField(blank=True, null=True, verbose_name='ID комментария-ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата модерации')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='blog.comment', verbose_name='Комментарий')),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='Asistent.commentmoderationcriteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Лог модерации комментария',
                'verbose_name_plural': 'Логи модерации комментариев',
                'ordering': ['-created_at'],
            },
        ),
    ]
