# Generated by Django 5.2.7 on 2025-10-10 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0003_commentmoderationlog'),
        ('blog', '0016_alter_like_unique_together_like_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttask',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='contenttask',
            name='article',
        ),
        migrations.RemoveField(
            model_name='contenttask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='contenttask',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='contenttask',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='contenttask',
            name='max_completions',
            field=models.IntegerField(default=1, help_text='Сколько авторов могут выполнить это задание', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Лимит выполнений'),
        ),
        migrations.AddField(
            model_name='contenttask',
            name='task_criteria',
            field=models.JSONField(default=dict, help_text='Особые требования к статье (имеют приоритет над общими критериями)', verbose_name='Специфические критерии для статьи'),
        ),
        migrations.AlterField(
            model_name='contenttask',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AuthorTaskRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклонения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='Asistent.contenttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отклонённое задание',
                'verbose_name_plural': 'Отклонённые задания',
                'ordering': ['-rejected_at'],
                'unique_together': {('author', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнено'), ('rejected_by_author', 'Отклонено автором'), ('rejected_by_ai', 'Отклонено AI'), ('approved', 'Одобрено')], default='in_progress', max_length=30, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('ai_moderation_result', models.JSONField(default=dict, help_text='Полный ответ от GigaChat', verbose_name='Результат AI модерации')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата взятия')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignment', to='blog.post', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Asistent.contenttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Назначение задания',
                'verbose_name_plural': 'Назначения заданий',
                'ordering': ['-taken_at'],
                'unique_together': {('task', 'author')},
            },
        ),
    ]
