# Generated by Django 5.2.7 on 2025-10-10 17:31

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def migrate_task_assignments(apps, schema_editor):
    """
    Миграция данных: создание TaskAssignment для заданий из старой структуры.
    Так как поля assigned_to и article уже удалены в миграции 0004,
    эта функция служит заглушкой на случай если будут данные для переноса в будущем.
    """
    ContentTask = apps.get_model('Asistent', 'ContentTask')
    TaskAssignment = apps.get_model('Asistent', 'TaskAssignment')
    
    # Обновляем статус заданий
    updated_active = ContentTask.objects.filter(status='taken').update(status='active')
    updated_active += ContentTask.objects.filter(status='submitted').update(status='active')
    updated_completed = ContentTask.objects.filter(status='approved').update(status='completed')
    updated_available = ContentTask.objects.filter(status='rejected').update(status='available')
    
    total_updated = updated_active + updated_completed + updated_available
    logger.info(f"Migrated task statuses: {total_updated} tasks updated")


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0004_remove_contenttask_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_task_assignments, reverse_code=migrations.RunPython.noop),
    ]
