# Generated by Django 5.2.7 on 2025-10-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0005_migrate_existing_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='video_sources_enabled',
            field=models.BooleanField(
                default=False,
                verbose_name='Использовать видеоисточники',
                help_text='Парсить контент из видеоплатформ'
            ),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='video_platforms',
            field=models.JSONField(
                default=list,
                verbose_name='Видеоплатформы для парсинга',
                help_text='Список: rutube, vk, dzen, pinterest, telegram'
            ),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_publish_to_platforms',
            field=models.JSONField(
                default=list,
                verbose_name='Автопубликация анонсов',
                help_text='На какие платформы публиковать анонсы статей'
            ),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='video_embed_in_articles',
            field=models.BooleanField(
                default=False,
                verbose_name='Встраивать видео в статьи',
                help_text='Автоматически добавлять релевантные видео в контент'
            ),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='telegram_channels',
            field=models.TextField(
                blank=True,
                verbose_name='Telegram каналы для парсинга',
                help_text='Username каналов через запятую (без @)'
            ),
        ),
    ]
