# Generated by Django 5.2.7 on 2025-10-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0006_add_video_fields_to_schedule'),
        ('blog', '0018_post_ai_draft_improved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aischedule',
            name='auto_publish_to_platforms',
            field=models.JSONField(default=list, help_text='Платформы для автоматической публикации анонсов', verbose_name='Автопубликация анонсов'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='telegram_channels',
            field=models.JSONField(default=list, help_text='Список channel_id для публикации', verbose_name='Telegram каналы'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='video_embed_in_articles',
            field=models.BooleanField(default=False, help_text='Добавлять видеоконтент в сгенерированные статьи', verbose_name='Встраивать видео в статьи'),
        ),
        migrations.CreateModel(
            name='AuthorStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(help_text='Например: "Легкий и вдохновляющий", "Экспертный научный"', max_length=200, verbose_name='Название стиля')),
                ('style_analysis', models.JSONField(default=dict, help_text='Результат автоматического анализа статей автора', verbose_name='Анализ стиля')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен для использования AI', verbose_name='Активен')),
                ('usage_count', models.IntegerField(default=0, help_text='Сколько раз AI использовал этот стиль', verbose_name='Использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('top_articles', models.ManyToManyField(blank=True, related_name='style_examples', to='blog.post', verbose_name='Лучшие статьи для обучения')),
            ],
            options={
                'verbose_name': 'Профиль стиля автора',
                'verbose_name_plural': 'Профили стилей авторов',
                'ordering': ['-usage_count', '-updated_at'],
            },
        ),
    ]
