# Generated by Django 5.2.7 on 2025-10-10 22:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0007_alter_aischedule_auto_publish_to_platforms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='mimic_author_style',
            field=models.ForeignKey(blank=True, help_text='AI будет имитировать стиль этого автора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mimicked_by_ai', to=settings.AUTH_USER_MODEL, verbose_name='Писать в стиле автора'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='style_strength',
            field=models.IntegerField(default=5, help_text='1 = слабая имитация, 10 = точная копия стиля', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Сила имитации стиля'),
        ),
    ]
