# Generated by Django 5.2.7 on 2025-10-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0008_aischedule_mimic_author_style_and_more'),
        ('blog', '0018_post_ai_draft_improved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='Вариант заголовка')),
                ('style', models.CharField(choices=[('question', 'Вопрос'), ('intrigue', 'Интрига'), ('fact', 'Факт'), ('benefit', 'Выгода'), ('how_to', 'Как сделать')], max_length=20, verbose_name='Стиль заголовка')),
                ('impressions', models.IntegerField(default=0, help_text='Сколько раз заголовок был показан', verbose_name='Показов')),
                ('clicks', models.IntegerField(default=0, help_text='Сколько раз по заголовку кликнули', verbose_name='Кликов')),
                ('is_active', models.BooleanField(default=True, help_text='Участвует в A/B тесте', verbose_name='Активен')),
                ('is_winner', models.BooleanField(default=False, help_text='Лучший вариант по CTR', verbose_name='Победитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_variants', to='blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Вариант заголовка',
                'verbose_name_plural': 'Варианты заголовков',
                'ordering': ['-created_at'],
            },
        ),
    ]
