# Generated by Django 5.2.7 on 2025-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0009_titlevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedarticle',
            name='api_calls_count',
            field=models.IntegerField(default=0, help_text='Количество вызовов GigaChat API для генерации этой статьи', verbose_name='Количество API вызовов'),
        ),
        migrations.AddField(
            model_name='aigeneratedarticle',
            name='generation_time_seconds',
            field=models.IntegerField(default=0, help_text='Время, затраченное на генерацию статьи в секундах', verbose_name='Время генерации (сек)'),
        ),
    ]
