# Generated by Django 5.2.7 on 2025-10-12 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0010_add_generation_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Автоматически генерируется из первого сообщения', max_length=200, verbose_name='Название диалога')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало диалога')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
                ('is_active', models.BooleanField(default=True, help_text='Текущий активный диалог', verbose_name='Активен')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Диалог с AI-агентом',
                'verbose_name_plural': 'Диалоги с AI-агентом',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('admin', 'Администратор'), ('ai', 'AI-агент')], max_length=10, verbose_name='Отправитель')),
                ('content', models.TextField(verbose_name='Содержание сообщения')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('question', 'Вопрос AI'), ('action', 'Предложение действия'), ('result', 'Результат выполнения')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Asistent.adminaiconversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_schedule', 'Создать расписание'), ('create_task', 'Создать задание'), ('run_generation', 'Запустить генерацию'), ('analyze_stats', 'Анализ статистики'), ('manage_bonuses', 'Управление бонусами'), ('convert_bonus_donation', 'Конвертация бонусы↔донаты'), ('author_report', 'Отчет по автору'), ('category_report', 'Отчет по категории'), ('payment_schedule', 'График выплат'), ('assign_bonus', 'Назначить бонус'), ('modify_formulas', 'Изменить формулы расчета'), ('create_category', 'Создать категорию'), ('publish_horoscopes', 'Опубликовать гороскопы')], max_length=50, verbose_name='Тип действия')),
                ('action_params', models.JSONField(default=dict, help_text='JSON с параметрами для выполнения', verbose_name='Параметры действия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрено'), ('executing', 'Выполняется'), ('completed', 'Выполнено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('result', models.JSONField(default=dict, help_text='JSON с результатами или ошибками', verbose_name='Результат выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='Asistent.adminaiconversation', verbose_name='Диалог')),
                ('message', models.ForeignKey(help_text='Сообщение AI, которое предложило действие', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='Asistent.adminaimessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Действие AI-агента',
                'verbose_name_plural': 'Действия AI-агента',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_type', models.CharField(choices=[('view', 'За просмотр'), ('like', 'За лайк'), ('comment', 'За комментарий'), ('donation_received', 'За полученный донат')], max_length=50, unique=True, verbose_name='Тип формулы')),
                ('value', models.DecimalField(decimal_places=2, help_text='Сколько рублей начисляется', max_digits=10, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('modified_by', models.ForeignKey(blank=True, help_text='Администратор или AI-агент', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Формула расчета бонусов',
                'verbose_name_plural': 'Формулы расчета бонусов',
            },
        ),
    ]
