# Generated by Django 5.2.7 on 2025-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0011_add_ai_agent_chat_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusformula',
            name='formula_type',
            field=models.CharField(choices=[('publication', 'За публикацию статьи'), ('view', 'За просмотр'), ('like', 'За лайк'), ('comment', 'За комментарий'), ('donation_received', 'За полученный донат')], max_length=50, unique=True, verbose_name='Тип формулы'),
        ),
    ]
