# Generated by Django 5.2.7 on 2025-10-12 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0012_update_bonus_formulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaiaction',
            name='action_type',
            field=models.CharField(choices=[('generate_article', 'Сгенерировать и опубликовать статью'), ('create_schedule', 'Создать расписание'), ('create_task', 'Создать задание'), ('run_generation', 'Запустить генерацию'), ('analyze_stats', 'Анализ статистики'), ('manage_bonuses', 'Управление бонусами'), ('convert_bonus_donation', 'Конвертация бонусы↔донаты'), ('author_report', 'Отчет по автору'), ('category_report', 'Отчет по категории'), ('payment_schedule', 'График выплат'), ('assign_bonus', 'Назначить бонус'), ('modify_formulas', 'Изменить формулы расчета'), ('create_category', 'Создать категорию'), ('publish_horoscopes', 'Опубликовать гороскопы'), ('list_rules', 'Показать правила'), ('add_rule', 'Добавить правило'), ('edit_rule', 'Изменить правило'), ('toggle_rule', 'Вкл/Выкл правило')], max_length=50, verbose_name='Тип действия'),
        ),
        migrations.CreateModel(
            name='AgentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('rule_type', models.CharField(choices=[('intent_parsing', 'Распознавание намерений'), ('response_generation', 'Генерация ответов'), ('action_execution', 'Выполнение действий'), ('general', 'Общее правило')], default='general', max_length=50, verbose_name='Тип правила')),
                ('rule_content', models.TextField(help_text='Описание правила поведения агента', verbose_name='Содержание правила')),
                ('priority', models.IntegerField(default=10, help_text='Чем меньше число, тем выше приоритет (1 = самый высокий)', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('examples', models.JSONField(default=list, help_text='Примеры применения правила', verbose_name='Примеры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, help_text='Администратор или AI-агент', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Правило AI-агента',
                'verbose_name_plural': 'Правила AI-агента',
                'ordering': ['priority', 'rule_name'],
            },
        ),
    ]
