# Generated by Django 5.2.7 on 2025-10-13 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0013_add_smart_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaiconversation',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='adminaimessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='agentrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bonusformula',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='min_word_count',
            field=models.IntegerField(default=1000, help_text='Рекомендуется 1000-1500 слов', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Минимум слов в статье'),
        ),
        migrations.DeleteModel(
            name='AdminAIAction',
        ),
        migrations.DeleteModel(
            name='AdminAIConversation',
        ),
        migrations.DeleteModel(
            name='AdminAIMessage',
        ),
        migrations.DeleteModel(
            name='AgentRule',
        ),
        migrations.DeleteModel(
            name='BonusFormula',
        ),
    ]
