# Generated by Django 5.1 on 2025-10-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0020_populate_knowledge_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aischedule',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='optimization_rules',
        ),
    ]
