# Generated by Django 5.1 on 2025-10-15 12:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0021_add_priority_to_knowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Вопрос пользователя или ключевые слова', max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Готовый ответ чат-бота (можно использовать HTML)', verbose_name='Ответ')),
                ('keywords', models.JSONField(default=list, help_text="Список слов для поиска: ['автор', 'заявка', 'статья']", verbose_name='Ключевые слова')),
                ('related_url', models.CharField(blank=True, help_text='Ссылка на статью или страницу (например: /visitor/apply-role/)', max_length=500, verbose_name='Ссылка')),
                ('priority', models.IntegerField(default=50, help_text='Чем выше - тем важнее (90+ критичные, показываются первыми)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать этот FAQ', verbose_name='Активен')),
                ('usage_count', models.IntegerField(default=0, help_text='Сколько раз был показан этот ответ', verbose_name='Количество использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'FAQ чат-бота',
                'verbose_name_plural': 'FAQ чат-бота',
                'ordering': ['-priority', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='Ты дружелюбный помощник сайта IdealImage.ru - женского портала о красоте, моде и здоровье.\n        \nТвоя задача:\n- Отвечать на вопросы о сайте вежливо и по-русски\n- Помогать пользователям найти нужную информацию\n- Объяснять, как стать автором\n- Предоставлять ссылки на полезные статьи\n- При необходимости предлагать связаться с администратором\n\nСтиль общения: дружелюбный, позитивный, но профессиональный.\nВсегда используй русский язык.', help_text='Инструкция для чат-бота: как себя вести, стиль общения', verbose_name='Системный промпт')),
                ('welcome_message', models.TextField(default='Здравствуйте! 👋 Я помощник IdealImage.ru. Чем могу помочь?', help_text='Первое сообщение при открытии чата', verbose_name='Приветственное сообщение')),
                ('use_ai', models.BooleanField(default=False, help_text='⚠️ Если выключено - только FAQ и поиск статей (экономия токенов)', verbose_name='Использовать GigaChat AI')),
                ('search_articles', models.BooleanField(default=True, help_text='Предлагать ссылки на релевантные статьи блога', verbose_name='Искать по статьям')),
                ('max_search_results', models.IntegerField(default=3, help_text='Сколько статей показывать в ответе (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Макс. результатов поиска')),
                ('admin_contact_enabled', models.BooleanField(default=True, help_text="Показывать кнопку 'Связаться с администратором'", verbose_name='Разрешить связь с админом')),
                ('admin_email', models.EmailField(default='admin@idealimage.ru', help_text='Куда отправлять сообщения от пользователей', max_length=254, verbose_name='Email администратора')),
                ('rate_limit_messages', models.IntegerField(default=10, help_text='Для защиты от спама (на одну сессию)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Лимит сообщений в час')),
                ('is_active', models.BooleanField(default=True, help_text='Глобальное включение/выключение чат-бота', verbose_name='Чат-бот активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Настройки чат-бота',
                'verbose_name_plural': 'Настройки чат-бота',
            },
        ),
        migrations.AlterField(
            model_name='aiknowledgebase',
            name='category',
            field=models.CharField(choices=[('промпты', 'Промпты'), ('правила', 'Правила'), ('примеры', 'Примеры'), ('команды', 'Команды'), ('faq', 'Частые вопросы'), ('инструкции', 'Инструкции'), ('источники', 'Источники')], max_length=100, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, verbose_name='Ключ сессии')),
                ('message', models.TextField(verbose_name='Сообщение пользователя')),
                ('response', models.TextField(verbose_name='Ответ чат-бота')),
                ('source', models.CharField(choices=[('faq', 'FAQ'), ('article_search', 'Поиск по статьям'), ('ai', 'GigaChat AI'), ('error', 'Ошибка')], max_length=20, verbose_name='Источник ответа')),
                ('found_articles', models.JSONField(blank=True, default=list, help_text='Список статей, предложенных в ответе', verbose_name='Найденные статьи')),
                ('processing_time', models.FloatField(default=0, help_text='Сколько времени заняла генерация ответа', verbose_name='Время обработки (сек)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='Asistent_ch_session_8ad3e1_idx'), models.Index(fields=['user', '-created_at'], name='Asistent_ch_user_id_781cbc_idx')],
            },
        ),
    ]
