# Generated by Django 5.1 on 2025-10-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0022_chatbotfaq_chatbotsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': '🤖 AI-Агент: Диалоги', 'verbose_name_plural': '🤖 AI-Агент: Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='aiknowledgebase',
            options={'ordering': ['-priority', '-usage_count', '-created_at'], 'verbose_name': '🤖 AI-Агент: База знаний', 'verbose_name_plural': '🤖 AI-Агент: База знаний'},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['timestamp'], 'verbose_name': '🤖 AI-Агент: Сообщения', 'verbose_name_plural': '🤖 AI-Агент: Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='aischedule',
            options={'ordering': ['-created_at'], 'verbose_name': '📋 Задания: Расписание AI', 'verbose_name_plural': '📋 Задания: Расписания AI'},
        ),
        migrations.AlterModelOptions(
            name='aitask',
            options={'ordering': ['-created_at'], 'verbose_name': '🤖 AI-Агент: Задачи', 'verbose_name_plural': '🤖 AI-Агент: Задачи'},
        ),
        migrations.AlterModelOptions(
            name='authornotification',
            options={'ordering': ['-created_at'], 'verbose_name': '✓ Модерация: Уведомления', 'verbose_name_plural': '✓ Модерация: Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='chatbotfaq',
            options={'ordering': ['-priority', '-usage_count'], 'verbose_name': '💬 Чат-бот: FAQ', 'verbose_name_plural': '💬 Чат-бот: FAQ'},
        ),
        migrations.AlterModelOptions(
            name='chatbotsettings',
            options={'verbose_name': '💬 Чат-бот: Настройки', 'verbose_name_plural': '💬 Чат-бот: Настройки'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '💬 Чат-бот: Сообщения', 'verbose_name_plural': '💬 Чат-бот: Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='contenttask',
            options={'ordering': ['-created_at'], 'verbose_name': '📋 Задания: Задание', 'verbose_name_plural': '📋 Задания: Задания'},
        ),
        migrations.AlterModelOptions(
            name='moderationcriteria',
            options={'ordering': ['-created_at'], 'verbose_name': '✓ Модерация: Критерии статей', 'verbose_name_plural': '✓ Модерация: Критерии статей'},
        ),
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '✓ Модерация: Логи статей', 'verbose_name_plural': '✓ Модерация: Логи статей'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'ordering': ['-taken_at'], 'verbose_name': '📋 Задания: Назначение', 'verbose_name_plural': '📋 Задания: Назначения'},
        ),
    ]
