# Generated by Django 5.1 on 2025-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0024_alter_aitask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='dzen_enabled',
            field=models.BooleanField(default=False, help_text='Автоматически публиковать статьи в Яндекс.Дзен', verbose_name='Публиковать в Дзен'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='rutube_enabled',
            field=models.BooleanField(default=False, help_text='Автоматически публиковать анонсы на Rutube', verbose_name='Публиковать на Rutube'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='vk_enabled',
            field=models.BooleanField(default=False, help_text='Автоматически публиковать анонсы в VK', verbose_name='Публиковать в VK'),
        ),
    ]
