# Generated by Django 5.1 on 2025-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0025_aischedule_dzen_enabled_aischedule_rutube_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('generate_article', 'Генерация статьи'), ('parse_video', 'Парсинг видео'), ('parse_audio', 'Парсинг аудио'), ('distribute_bonuses', 'Распределение бонусов'), ('distribute_donations', 'Распределение донатов'), ('create_schedule', 'Создание расписания'), ('post_comment', 'Публикация комментария'), ('add_like', 'Добавление лайка'), ('moderate_content', 'Модерация контента'), ('analyze_statistics', 'Анализ статистики'), ('optimize_schedule', 'Оптимизация расписания'), ('publish_to_social', 'Публикация в соцсети'), ('schedule_posts', 'Создание расписания публикаций'), ('reply_to_comment', 'Ответ на комментарий в соцсети'), ('reply_to_message', 'Ответ в переписке'), ('analyze_channel', 'Анализ канала'), ('optimize_posting', 'Оптимизация времени публикации'), ('create_ad_campaign', 'Создание рекламной кампании'), ('crosspost_content', 'Кросс-постинг контента'), ('ad_show_places', 'Показать рекламные места'), ('ad_statistics', 'Статистика рекламы'), ('ad_activate_banner', 'Активировать баннер'), ('ad_deactivate_banner', 'Деактивировать баннер'), ('ad_list_banners', 'Список баннеров'), ('ad_insert_in_article', 'Вставить рекламу в статью')], max_length=50, verbose_name='Тип задачи'),
        ),
    ]
