# Generated by Django 5.1 on 2025-10-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0026_alter_aitask_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigaChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_balance_after_requests', models.IntegerField(default=1, help_text='Частота проверки баланса токенов', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проверять баланс после N запросов')),
                ('current_model', models.CharField(default='GigaChat', help_text='Активная модель GigaChat', max_length=50, verbose_name='Текущая модель')),
                ('auto_switch_enabled', models.BooleanField(default=True, help_text='Автоматически переключаться на другую модель при исчерпании токенов', verbose_name='Автопереключение моделей')),
                ('models_priority', models.JSONField(default=list, help_text='Порядок переключения моделей', verbose_name='Приоритет моделей')),
                ('request_counter', models.IntegerField(default=0, help_text='Внутренний счётчик для определения момента проверки баланса', verbose_name='Счётчик запросов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': '🤖 GigaChat: Настройки',
                'verbose_name_plural': '🤖 GigaChat: Настройки',
            },
        ),
        migrations.CreateModel(
            name='GigaChatUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='GigaChat, GigaChat-Max, GigaChat-Pro', max_length=50, unique=True, verbose_name='Название модели')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Токенов использовано')),
                ('tokens_remaining', models.IntegerField(blank=True, null=True, verbose_name='Токенов осталось')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Всего запросов')),
                ('successful_requests', models.IntegerField(default=0, verbose_name='Успешных запросов')),
                ('failed_requests', models.IntegerField(default=0, verbose_name='Неудачных запросов')),
                ('last_check_at', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '🤖 GigaChat: Статистика модели',
                'verbose_name_plural': '🤖 GigaChat: Статистика моделей',
                'ordering': ['model_name'],
            },
        ),
    ]
