# Generated by Django 5.1 on 2025-10-29 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0027_gigachatsettings_gigachatusagestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigachatsettings',
            name='alert_threshold_percent',
            field=models.IntegerField(default=20, help_text='При балансе ниже этого процента - желтый алерт в Dashboard', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог алерта (%)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='embeddings_enabled',
            field=models.BooleanField(default=True, help_text='Использовать GigaChat-Embeddings для RAG и векторного поиска', verbose_name='Embeddings включен'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='lite_enabled',
            field=models.BooleanField(default=True, help_text='Использовать GigaChat Lite для простых задач', verbose_name='Lite включен'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='max_enabled',
            field=models.BooleanField(default=True, help_text='Использовать GigaChat Max для сложных задач', verbose_name='Max включен'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='preventive_switch_threshold',
            field=models.IntegerField(default=10, help_text='При балансе ниже этого процента - автоматически переключаемся на fallback модель', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог превентивного переключения (%)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='price_embeddings',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='10M токенов = 400₽ → 1M = 40₽', max_digits=10, verbose_name='Цена Embeddings (₽/1M)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='price_lite',
            field=models.DecimalField(decimal_places=2, default=194.0, help_text='30M токенов = 5,820₽ → 1M = 194₽', max_digits=10, verbose_name='Цена Lite (₽/1M)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=1950.0, help_text='1M токенов = 1,950₽', max_digits=10, verbose_name='Цена Max (₽/1M)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='price_pro',
            field=models.DecimalField(decimal_places=2, default=1500.0, help_text='1M токенов = 1,500₽', max_digits=10, verbose_name='Цена Pro (₽/1M)'),
        ),
        migrations.AddField(
            model_name='gigachatsettings',
            name='pro_enabled',
            field=models.BooleanField(default=True, help_text='Использовать GigaChat Pro для средних задач', verbose_name='Pro включен'),
        ),
        migrations.AddField(
            model_name='gigachatusagestats',
            name='cost_today',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Расходы на API за текущий день', max_digits=10, verbose_name='Стоимость сегодня (₽)'),
        ),
        migrations.AddField(
            model_name='gigachatusagestats',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Все расходы на API за все время', max_digits=10, verbose_name='Общая стоимость (₽)'),
        ),
        migrations.AddField(
            model_name='gigachatusagestats',
            name='last_daily_reset',
            field=models.DateTimeField(blank=True, help_text='Дата последнего сброса tokens_used_today и cost_today (в 00:00)', null=True, verbose_name='Последний сброс дневной статистики'),
        ),
        migrations.AddField(
            model_name='gigachatusagestats',
            name='tokens_used_today',
            field=models.IntegerField(default=0, help_text='Счетчик токенов за текущий день (сбрасывается в 00:00)', verbose_name='Токенов использовано сегодня'),
        ),
    ]
