# Generated by Django 5.1 on 2025-11-02 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asistent", "0028_expand_gigachat_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Для поиска похожих диалогов (генерируется для admin-сообщений)",
                null=True,
                verbose_name="Векторное представление",
            ),
        ),
        migrations.AddField(
            model_name="chatbotfaq",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Для семантического поиска FAQ (автогенерируется)",
                null=True,
                verbose_name="Векторное представление",
            ),
        ),
        migrations.AlterField(
            model_name="chatbotsettings",
            name="system_prompt",
            field=models.TextField(
                default="Ты дружелюбный менеджер сайта IdealImage.ru - женского портала о красоте, моде и здоровье.\n        Твоя задача:\n        - Отвечать на вопросы о сайте вежливо и по-русски\n        - Помогать пользователям найти нужную информацию\n        - Объяснять, как стать автором\n        - Предоставлять ссылки на полезные статьи\n        - При необходимости предлагать связаться с администратором\n        \n        Стиль общения: дружелюбный, позитивный, но профессиональный.\n        Всегда используй русский язык.",
                help_text="Инструкция для чат-бота: как себя вести, стиль общения",
                verbose_name="Системный промпт",
            ),
        ),
        migrations.AddIndex(
            model_name="aiknowledgebase",
            index=models.Index(
                fields=["category", "-priority"], name="kb_cat_prior_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiknowledgebase",
            index=models.Index(fields=["-usage_count"], name="kb_usage_idx"),
        ),
        migrations.AddIndex(
            model_name="aiknowledgebase",
            index=models.Index(
                fields=["is_active", "category"], name="kb_active_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiknowledgebase",
            index=models.Index(fields=["-created_at"], name="kb_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "timestamp"], name="aimsg_conv_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["role", "timestamp"], name="aimsg_role_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotfaq",
            index=models.Index(
                fields=["is_active", "-priority"], name="faq_active_prior_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotfaq",
            index=models.Index(fields=["-usage_count"], name="faq_usage_idx"),
        ),
    ]
