# Generated by Django 5.1 on 2025-11-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0029_aimessage_embedding_chatbotfaq_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Выберите шаблон для генерации статей. Если не выбран - используется стандартный', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='Asistent.prompttemplate', verbose_name='Шаблон промпта'),
        ),
    ]
