# Generated by Django 5.1 on 2025-11-04 00:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0030_add_prompt_template_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='ad_frequency',
            field=models.IntegerField(default=500, help_text='Вставлять рекламный блок каждые N слов (рекомендуется 400-600)', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Частота рекламы (слов)'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='add_faq_blocks',
            field=models.BooleanField(default=True, help_text='Генерировать раздел "Частые вопросы" в статьях', verbose_name='Добавлять FAQ блоки'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='add_internal_links',
            field=models.BooleanField(default=True, help_text='Автоматически вставлять ссылки на другие статьи сайта по смыслу', verbose_name='Добавлять внутренние ссылки (перелиновка)'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='ai_correction_enabled',
            field=models.BooleanField(default=False, help_text='Разрешить AI исправлять ошибки и улучшать текст', verbose_name='AI корректировка текста'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_comment_count',
            field=models.IntegerField(default=2, help_text='Сколько комментариев добавлять (рекомендуется 1-3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Количество автокомментариев'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_comment_enabled',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять комментарии от ботов', verbose_name='Авто-комментирование'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_like_count',
            field=models.IntegerField(default=5, help_text='Сколько лайков добавлять (рекомендуется 3-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество автолайков'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_like_enabled',
            field=models.BooleanField(default=False, help_text='Автоматически ставить лайки от фейковых пользователей после публикации', verbose_name='Авто-лайкинг'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_moderate',
            field=models.BooleanField(default=True, help_text='Проверять статью AI модератором перед публикацией', verbose_name='Автомодерация перед публикацией'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='auto_seo_optimize',
            field=models.BooleanField(default=True, help_text='Автоматически оптимизировать SEO статьи после публикации (alt-теги, мета-описание)', verbose_name='Авто SEO-оптимизация'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='comment_prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_schedules', to='Asistent.prompttemplate', verbose_name='Шаблон промпта для комментариев'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='Например: 0 9,18 * * * (в 9:00 и 18:00 каждый день), 30 8 * * 4 (каждый четверг в 8:30)', max_length=100, verbose_name='Cron выражение'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='[1,2,3,4,5] для пн-пт, [4] для четверга, [6,7] для выходных. Пусто = все дни', verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='expand_to_min_words',
            field=models.BooleanField(default=False, help_text='Если статья меньше min_word_count - дополнить её', verbose_name='Расширять до минимума слов'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='faq_prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_schedules', to='Asistent.prompttemplate', verbose_name='Шаблон промпта для FAQ'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='image_generation_prompt',
            field=models.TextField(blank=True, help_text='Описание какое изображение генерировать. Пример: красивая девушка с макияжем, студийное фото', verbose_name='Промпт для генерации изображения'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='image_source_type',
            field=models.CharField(choices=[('parse', 'Парсить из источников'), ('generate', 'Генерировать через GigaChat'), ('stock', 'Брать из стоковых (Unsplash/Pixabay)'), ('none', 'Без изображения')], default='parse', max_length=20, verbose_name='Источник изображения'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='insert_ads',
            field=models.BooleanField(default=False, help_text='Автоматически вставлять рекламу в статью', verbose_name='Вставлять рекламные блоки'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='internal_links_count',
            field=models.IntegerField(default=3, help_text='Сколько ссылок на статьи сайта вставлять (рекомендуется 2-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Количество внутренних ссылок'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='is_multi_task',
            field=models.BooleanField(default=False, help_text='Создавать несколько статей из одного списка (например 12 гороскопов для знаков зодиака)', verbose_name='Мульти-задача'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='moderation_criteria',
            field=models.ForeignKey(blank=True, help_text='Правила проверки качества статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_schedules', to='Asistent.moderationcriteria', verbose_name='Критерии модерации'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='multi_task_items',
            field=models.JSONField(blank=True, default=list, help_text='Список элементов. Например: ["Овен", "Телец", "Близнецы", ...]. Для каждого будет создана отдельная статья', verbose_name='Элементы мульти-задачи'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='multi_task_variable_name',
            field=models.CharField(blank=True, default='item', help_text='Имя переменной для подстановки в промпт. Например: zodiac_sign, category_item', max_length=50, verbose_name='Название переменной'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='referral_links_enabled',
            field=models.BooleanField(default=False, help_text='Добавлять партнёрские/реферальные ссылки в текст', verbose_name='Вставлять реферальные ссылки'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='referral_prompt_template',
            field=models.ForeignKey(blank=True, help_text='Промпт для генерации реферального текста с партнёрскими ссылками', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_schedules', to='Asistent.prompttemplate', verbose_name='Шаблон для реферальных ссылок'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='schedule_type',
            field=models.CharField(choices=[('frequency', 'По частоте (daily/weekly)'), ('cron', 'Cron выражение'), ('specific_times', 'Конкретные времена')], default='frequency', max_length=20, verbose_name='Тип расписания'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='specific_times',
            field=models.JSONField(blank=True, default=list, help_text='Список времён. Пример: ["09:00", "14:00", "19:00"]', verbose_name='Конкретные времена запуска'),
        ),
    ]
