# Generated by Django 5.1 on 2025-11-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0031_add_full_automation_fields'),
        ('blog', '0027_add_ai_help_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта/сервиса')),
                ('link_type', models.CharField(choices=[('product', '🛍️ Продукт'), ('service', '🎯 Сервис'), ('course', '📚 Курс'), ('software', '💻 Программа'), ('other', '🔗 Другое')], default='product', max_length=20, verbose_name='Тип ссылки')),
                ('url', models.URLField(help_text='Полная ссылка с реферальным кодом', verbose_name='Реферальная ссылка')),
                ('description', models.TextField(help_text='Краткое описание для AI (что это, для кого, преимущества)', verbose_name='Описание продукта')),
                ('keywords', models.TextField(blank=True, help_text='Через запятую. Когда в статье упоминаются эти слова - AI может вставить ссылку', verbose_name='Ключевые слова')),
                ('insertion_template', models.TextField(blank=True, help_text='Как AI должен вставлять ссылку. Если пусто - AI придумает сам', verbose_name='Шаблон вставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('usage_count', models.IntegerField(default=0, help_text='Сколько раз ссылка была вставлена в статьи', verbose_name='Использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, help_text='Для какой категории статей подходит эта ссылка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '🔗 Реферальная ссылка',
                'verbose_name_plural': '🔗 Реферальные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
