# Generated by Django 5.1 on 2025-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0032_add_referral_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='custom_image_prompt',
            field=models.TextField(blank=True, help_text='Переопределяет стандартный промпт. Переменные: {category}, {zodiac_sign}, {season}, {title}', verbose_name='Кастомный промпт для изображений'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='gigachat_model',
            field=models.CharField(choices=[('GigaChat', 'GigaChat Lite (194₽/1M) - быстро, дёшево'), ('GigaChat-Pro', 'GigaChat Pro (1500₽/1M) - баланс'), ('GigaChat-Max', 'GigaChat Max (1950₽/1M) - максимальное качество')], default='GigaChat', help_text='Выбор модели влияет на качество и стоимость генерации', max_length=50, verbose_name='Модель GigaChat для генерации текста'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='Публиковать статьи в черновики вместо автопубликации', verbose_name='Тестовый режим'),
        ),
    ]
