# Generated by Django 5.1 on 2025-11-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0033_aischedule_custom_image_prompt_and_more'),
        ('blog', '0027_add_ai_help_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='auto_process_image',
            field=models.BooleanField(default=True, help_text='Переименование по-английски, оптимизация размера, формат, индексация', verbose_name='AI обработка изображения'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='blog_category',
            field=models.ForeignKey(blank=True, help_text='В какую категорию публиковать статью', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория в блоге'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_source_type',
            field=models.CharField(blank=True, choices=[('parse', 'Парсить из источников + переписать'), ('generate', 'Полностью генерировать AI'), ('hybrid', 'Гибрид: парсить темы + генерировать текст')], default='hybrid', max_length=20, verbose_name='Источник контента'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_source_urls',
            field=models.TextField(blank=True, help_text='По одному на строке. Если пусто - используется из AISchedule', verbose_name='URL источников для контента'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='image_generation_criteria',
            field=models.TextField(blank=True, help_text='Промпт для генерации. Если пусто - AI выбирает сам. Переменные: {zodiac_sign}, {season}, {category}, {title}', verbose_name='Критерии генерации изображения'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='image_search_criteria',
            field=models.TextField(blank=True, help_text='По каким критериям искать. Если пусто - AI выбирает по категории и названию. Переменные: {zodiac_sign}, {category}, {title}', verbose_name='Критерии поиска изображения'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='image_source_type',
            field=models.CharField(blank=True, choices=[('upload', 'Загрузить (модератор загружает)'), ('search_db', 'Поиск в нашей базе'), ('parse_web', 'Парсинг из интернета'), ('generate_auto', 'Генерация - на усмотрение AI'), ('generate_custom', 'Генерация - с кастомным промптом'), ('none', 'Без изображения')], default='generate_auto', max_length=20, verbose_name='Источник главного изображения'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='parse_first_paragraph',
            field=models.BooleanField(default=False, help_text='Спарсить первый абзац с сайтов и использовать как основу', verbose_name='Парсить первый абзац из источников'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='tags_criteria',
            field=models.TextField(blank=True, help_text='Через запятую. В кавычках "слово" = буквально, без кавычек знак_зодиака = подобрать по смыслу. Переменные: {zodiac_sign}, {category}', verbose_name='Критерии для тегов'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='title_criteria',
            field=models.TextField(blank=True, help_text='Инструкции AI как формировать заголовок. Переменные: {zodiac_sign}, {date}, {category}', verbose_name='Критерии для заголовка'),
        ),
    ]
