# Generated by Django 5.1 on 2025-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0034_prompttemplate_auto_process_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='uploaded_media',
            field=models.FileField(blank=True, help_text='Для режима "Загрузить (модератор загружает)". AI обработает автоматически', null=True, upload_to='prompt_templates/', verbose_name='Загруженный файл (изображение/видео)'),
        ),
    ]
