# Generated by Django 5.1 on 2025-11-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0035_prompttemplate_uploaded_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aischedule',
            name='ad_frequency',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='add_faq_blocks',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='add_internal_links',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='ai_correction_enabled',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_comment_count',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_comment_enabled',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_like_count',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_like_enabled',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_moderate',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='auto_seo_optimize',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='comment_prompt_template',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='cron_expression',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='custom_image_prompt',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='expand_to_min_words',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='faq_prompt_template',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='gigachat_model',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='image_generation_prompt',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='image_source_type',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='insert_ads',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='internal_links_count',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='is_multi_task',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='moderation_criteria',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='multi_task_items',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='multi_task_variable_name',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='referral_links_enabled',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='referral_prompt_template',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='specific_times',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='test_mode',
        ),
        migrations.AddField(
            model_name='aischedule',
            name='current_run_count',
            field=models.IntegerField(default=0, help_text='Автоматически увеличивается при каждом запуске', verbose_name='Текущий счётчик запусков'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='dynamic_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с типами: cycle_list, current_date, api_call, random_choice', verbose_name='Динамические параметры'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='max_runs',
            field=models.IntegerField(blank=True, help_text='Для тренингов: 21 день = 21 запуск. Пусто = бесконечно', null=True, verbose_name='Максимум запусков'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Например: 08:30 для запуска каждый день в 8:30. Если пусто - запуск по частоте.', null=True, verbose_name='Точное время запуска'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='static_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"topic": "гороскоп", "style": "по-фрейду"}', verbose_name='Статические параметры'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='task_type',
            field=models.CharField(choices=[('generate_article', 'Генерация статей'), ('add_likes', 'Лайки (случайные статьи)'), ('add_comments', 'Комментарии (случайные статьи)')], default='generate_article', help_text='Что должно выполняться по расписанию', max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Если выбран - использовать промпт вместо парсинга источников', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='Asistent.prompttemplate', verbose_name='Шаблон промпта'),
        ),
        migrations.DeleteModel(
            name='ReferralLink',
        ),
    ]
