# Generated by Django 5.1 on 2025-11-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0036_remove_aischedule_ad_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aischedule',
            name='source_urls',
            field=models.TextField(blank=True, help_text='Сайты для мониторинга новостей (не требуется если выбран промпт)', verbose_name='URL источников (по одному на строке)'),
        ),
    ]
