# Generated by Django 5.1 on 2025-11-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0037_source_urls_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='default_author',
            field=models.ForeignKey(blank=True, help_text='Кто будет автором сгенерированных статей (если пусто - используется ai_assistant или текущий пользователь)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор статей'),
        ),
    ]
