# Generated by Django 5.1 on 2025-11-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0038_add_default_author_to_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='strategy_options',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры стратегии (например, имя системной задачи, правила ретраев).', verbose_name='Опции стратегии'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='strategy_type',
            field=models.CharField(choices=[('prompt', 'Промпт-шаблон'), ('system', 'Системная задача'), ('manual', 'Ручной режим')], default='prompt', help_text='Определяет способ выполнения расписания: промпт, системная задача или ручной режим.', max_length=20, verbose_name='Тип стратегии'),
        ),
        migrations.CreateModel(
            name='AIScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('prompt', 'Промпт-шаблон'), ('system', 'Системная задача'), ('manual', 'Ручной режим')], max_length=20, verbose_name='Стратегия')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично')], default='running', max_length=20, verbose_name='Статус')),
                ('created_count', models.IntegerField(default=0, verbose_name='Создано объектов')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='Asistent.aischedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'AI расписание: запуск',
                'verbose_name_plural': 'AI расписание: запуски',
                'ordering': ['-started_at'],
            },
        ),
    ]
