# Generated by Django 5.1 on 2025-11-08 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0040_merge_0038_0039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('template_text', models.TextField(verbose_name='Текст промпта')),
                ('variables', models.JSONField(default=list, verbose_name='Переменные')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('title_criteria', models.TextField(blank=True, verbose_name='Критерии заголовка')),
                ('image_search_criteria', models.TextField(blank=True, verbose_name='Критерии поиска изображения')),
                ('image_generation_criteria', models.TextField(blank=True, verbose_name='Критерии генерации изображения')),
                ('tags_criteria', models.TextField(blank=True, verbose_name='Критерии тегов')),
                ('change_summary', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='Автор версии')),
            ],
            options={
                'verbose_name': 'Версия промпта',
                'verbose_name_plural': 'Версии промптов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='current_version',
            field=models.IntegerField(default=1, verbose_name='Текущая версия'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='last_change_summary',
            field=models.TextField(blank=True, verbose_name='Последнее описание изменений'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
        migrations.AddField(
            model_name='prompttemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Asistent.prompttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplateversion',
            unique_together={('template', 'version')},
        ),
    ]
