# Generated by Django 5.1 on 2025-11-08 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Asistent", "0041_prompttemplateversion_remove_aifeedback_created_by_and_more"),
        ("Asistent", "0042_seed_prompt_templates"),
    ]

    operations = []
