# Generated by Django 5.1 on 2025-11-11 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0047_moderationcriteria_rule_config_fields'),
        ('Visitor', '0009_alter_pisaka_psevdonim_alter_profile_spez'),
        ('blog', '0028_post_ai_improvement_task_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorstyleprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commentmoderationcriteria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модерация: Критерий комментариев', 'verbose_name_plural': 'Модерация: Критерии комментариев'},
        ),
        migrations.AlterModelOptions(
            name='commentmoderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модерация: Журнал комментариев', 'verbose_name_plural': 'Модерация: Журнал комментариев'},
        ),
        migrations.AlterModelOptions(
            name='moderationcriteria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модерация: Набор правил', 'verbose_name_plural': 'Модерация: Наборы правил'},
        ),
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модерация: Журнал статей', 'verbose_name_plural': 'Модерация: Журнал статей'},
        ),
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='ai_response',
            field=models.TextField(blank=True, verbose_name='Ответ AI'),
        ),
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='api_calls_count',
            field=models.IntegerField(default=0, verbose_name='Количество API вызовов'),
        ),
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='generation_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Время генерации (сек)'),
        ),
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='source_urls',
            field=models.TextField(blank=True, verbose_name='Источники'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='auto_publish_to_platforms',
            field=models.JSONField(default=list, verbose_name='Автопубликация анонсов'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='current_run_count',
            field=models.IntegerField(default=0, verbose_name='Текущий счётчик запусков'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='dynamic_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Динамические параметры'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='dzen_enabled',
            field=models.BooleanField(default=False, verbose_name='Публиковать в Дзен'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='max_runs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум запусков'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='mimic_author_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mimicked_by_ai', to=settings.AUTH_USER_MODEL, verbose_name='Писать в стиле автора'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='min_word_count',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Минимум слов в статье'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='Asistent.prompttemplate', verbose_name='Шаблон промпта'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='rutube_enabled',
            field=models.BooleanField(default=False, verbose_name='Публиковать на Rutube'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Точное время запуска'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='source_urls',
            field=models.TextField(blank=True, verbose_name='URL источников (по одному на строке)'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='static_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Статические параметры'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='strategy_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Опции стратегии'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='strategy_type',
            field=models.CharField(choices=[('prompt', 'Промпт-шаблон'), ('system', 'Системная задача'), ('manual', 'Ручной режим')], default='prompt', max_length=20, verbose_name='Тип стратегии'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='style_strength',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Сила имитации стиля'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='task_type',
            field=models.CharField(choices=[('generate_article', 'Генерация статей'), ('add_likes', 'Лайки (случайные статьи)'), ('add_comments', 'Комментарии (случайные статьи)')], default='generate_article', max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='telegram_channels',
            field=models.JSONField(default=list, verbose_name='Telegram каналы'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='video_embed_in_articles',
            field=models.BooleanField(default=False, verbose_name='Встраивать видео в статьи'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='video_platforms',
            field=models.JSONField(default=list, verbose_name='Видеоплатформы для парсинга'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='video_sources_enabled',
            field=models.BooleanField(default=False, verbose_name='Использовать видеоисточники'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='vk_enabled',
            field=models.BooleanField(default=False, verbose_name='Публиковать в VK'),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('generate_article', 'Генерация статьи'), ('parse_video', 'Парсинг видео'), ('parse_audio', 'Парсинг аудио'), ('distribute_bonuses', 'Распределение бонусов'), ('post_comment', 'Публикация комментария'), ('add_like', 'Добавление лайка'), ('optimize_schedule', 'Оптимизация расписания'), ('publish_to_social', 'Публикация в соцсети'), ('schedule_posts', 'Создание расписания публикаций'), ('reply_to_comment', 'Ответ на комментарий в соцсети'), ('reply_to_message', 'Ответ в переписке'), ('analyze_channel', 'Анализ канала'), ('optimize_posting', 'Оптимизация времени публикации'), ('create_ad_campaign', 'Создание рекламной кампании'), ('crosspost_content', 'Кросс-постинг контента'), ('ad_show_places', 'Показать рекламные места'), ('ad_statistics', 'Статистика рекламы'), ('ad_activate_banner', 'Активировать баннер'), ('ad_deactivate_banner', 'Деактивировать баннер'), ('ad_list_banners', 'Список баннеров'), ('ad_insert_in_article', 'Вставить рекламу в статью')], max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='authorstyleprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='authorstyleprofile',
            name='style_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Результат автоматического анализа статей автора', null=True, verbose_name='Анализ стиля'),
        ),
        migrations.AlterField(
            model_name='authorstyleprofile',
            name='style_name',
            field=models.CharField(blank=True, default='', help_text='Например: "Легкий и вдохновляющий", "Экспертный научный"', max_length=200, null=True, verbose_name='Название стиля'),
        ),
        migrations.AlterField(
            model_name='authorstyleprofile',
            name='top_articles',
            field=models.ManyToManyField(blank=True, to='blog.post', verbose_name='Лучшие статьи для обучения'),
        ),
        migrations.AlterField(
            model_name='authorstyleprofile',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Использований'),
        ),
        migrations.AlterField(
            model_name='commentmoderationcriteria',
            name='action',
            field=models.CharField(choices=[('delete', 'Удалить'), ('correct', 'Исправить'), ('reply', 'Ответить шаблоном'), ('flag', 'Пометить для проверки')], default='delete', max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='commentmoderationcriteria',
            name='criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Произвольный JSON с настройками: forbidden_words, min_length и т.д.', verbose_name='Правила (JSON)'),
        ),
        migrations.AlterField(
            model_name='commentmoderationcriteria',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название критерия'),
        ),
        migrations.AlterField(
            model_name='commentmoderationcriteria',
            name='reply_template',
            field=models.TextField(blank=True, help_text='Используется если действие = reply. Доступны плейсхолдеры {author}, {reason}.', verbose_name='Шаблон ответа'),
        ),
        migrations.AlterField(
            model_name='commentmoderationlog',
            name='action_taken',
            field=models.CharField(choices=[('delete', 'Удалить'), ('correct', 'Исправить'), ('reply', 'Ответить шаблоном'), ('flag', 'Пометить для проверки')], max_length=20, verbose_name='Совершённое действие'),
        ),
        migrations.AlterField(
            model_name='commentmoderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='commentmoderationlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='moderationcriteria',
            name='criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Произвольный JSON с дополнительными требованиями. Используется для обратной совместимости.', verbose_name='Наследуемые параметры (legacy)'),
        ),
        migrations.AlterField(
            model_name='moderationcriteria',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите, для чего используется данный набор правил.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='moderationcriteria',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название набора правил'),
        ),
        migrations.AlterField(
            model_name='moderationcriteria',
            name='rule_config',
            field=models.JSONField(blank=True, default=dict, help_text='Конфигурация правил модерации. Ожидается структура вида {"global": [...], "roles": {"author_with_ai": [...]}, "categories": {"beauty": [...]}}. Каждое правило должно содержать уникальный "code". Если "enabled": false — правило будет отключено.', verbose_name='Матрица правил'),
        ),
        migrations.AlterField(
            model_name='moderationcriteria',
            name='slug',
            field=models.SlugField(blank=True, help_text='Будет использован как идентификатор профиля модерации. Если не заполнено — сформируется автоматически из названия.', max_length=100, null=True, unique=True, verbose_name='Человекочитаемый код'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='ai_response',
            field=models.JSONField(default=dict, help_text='Полный ответ/квитанция от AI, фиксирующая детали модерации', verbose_name='Ответ AI'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('article_generation', 'Генерация статей'), ('moderation', 'Модерация'), ('commenting', 'Комментирование'), ('analysis', 'Анализ'), ('scheduling', 'Расписание'), ('system', 'Системные')], default='', max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='content_source_urls',
            field=models.TextField(blank=True, default='', help_text='По одному на строке. Если пусто - используется из AISchedule', null=True, verbose_name='URL источников для контента'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='image_generation_criteria',
            field=models.TextField(blank=True, default='', help_text='Промпт для генерации. Если пусто - AI выбирает сам. Переменные: {zodiac_sign}, {season}, {category}, {title}', null=True, verbose_name='Критерии генерации изображения'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='image_search_criteria',
            field=models.TextField(blank=True, default='', help_text='По каким критериям искать. Если пусто - AI выбирает по категории и названию. Переменные: {zodiac_sign}, {category}, {title}', null=True, verbose_name='Критерии поиска изображения'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='tags_criteria',
            field=models.TextField(blank=True, default='', help_text='Через запятую. В кавычках "слово" = буквально, без кавычек знак_зодиака = подобрать по смыслу. Переменные: {zodiac_sign}, {category}', null=True, verbose_name='Критерии для тегов'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='template',
            field=models.TextField(blank=True, default='', help_text='Используйте {переменные} для подстановки', null=True, verbose_name='Шаблон промпта'),
        ),
    ]
