# Generated by Django 5.1 on 2025-11-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0048_remove_aifeedback_created_by_remove_aifeedback_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('article', 'Статьи'), ('comment', 'Комментарии'), ('seo', 'SEO'), ('distribution', 'Дистрибуция'), ('donations', 'Донаты'), ('custom', 'Пользовательский')], default='article', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PipelineRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успех'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='Asistent.automationpipeline')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
