# Generated by Django 5.1 on 2025-11-14 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0054_update_prompt_template_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', help_text='Используется, если выбран тип "По cron-выражению"', max_length=120, verbose_name='CRON выражение'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='interval_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал, минут'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='payload_template',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-данные, которые будут переданы в пайплайн при запуске', verbose_name='Payload для пайплайна'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_schedules', to='Asistent.automationpipeline', verbose_name='Пайплайн автоматизации'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='pipeline_slug',
            field=models.CharField(blank=True, default='', help_text='Например: daily-horoscope-flow', max_length=160, verbose_name='Slug пайплайна (если нет связи)'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='schedule_kind',
            field=models.CharField(choices=[('daily', 'Ежедневно в указанное время'), ('weekly', 'Раз в неделю'), ('interval', 'Через каждые N минут'), ('cron', 'По cron-выражению')], default='daily', max_length=16, verbose_name='Тип расписания'),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели (для еженедельных запусков)'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='strategy_type',
            field=models.CharField(choices=[('prompt', 'Промпт-шаблон'), ('system', 'Системная задача'), ('manual', 'Ручной режим'), ('pipeline', 'Пайплайн автоматизации')], default='prompt', max_length=20, verbose_name='Тип стратегии'),
        ),
        migrations.AlterField(
            model_name='aischedulerun',
            name='strategy_type',
            field=models.CharField(choices=[('prompt', 'Промпт-шаблон'), ('system', 'Системная задача'), ('manual', 'Ручной режим'), ('pipeline', 'Пайплайн автоматизации')], max_length=20, verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('generate_article', 'Генерация статьи'), ('parse_video', 'Парсинг видео'), ('parse_audio', 'Парсинг аудио'), ('distribute_bonuses', 'Распределение бонусов'), ('optimize_schedule', 'Оптимизация расписания'), ('publish_to_social', 'Публикация в соцсети'), ('schedule_posts', 'Создание расписания публикаций'), ('reply_to_comment', 'Ответ на комментарий в соцсети'), ('reply_to_message', 'Ответ в переписке'), ('analyze_channel', 'Анализ канала'), ('optimize_posting', 'Оптимизация времени публикации'), ('create_ad_campaign', 'Создание рекламной кампании'), ('crosspost_content', 'Кросс-постинг контента'), ('ad_show_places', 'Показать рекламные места'), ('ad_statistics', 'Статистика рекламы'), ('ad_activate_banner', 'Активировать баннер'), ('ad_deactivate_banner', 'Деактивировать баннер'), ('ad_list_banners', 'Список баннеров'), ('ad_insert_in_article', 'Вставить рекламу в статью')], max_length=50, verbose_name='Тип задачи'),
        ),
    ]
