# Generated by Django 5.1 on 2025-11-14 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0055_remove_aifeedback_created_by_remove_aifeedback_task_and_more'),
        ('Visitor', '0009_alter_pisaka_psevdonim_alter_profile_spez'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aifeedback',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aifeedback',
            name='task',
        ),
        migrations.DeleteModel(
            name='AIMemory',
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='template',
        ),
        migrations.RemoveField(
            model_name='titlevariant',
            name='post',
        ),
        migrations.RemoveField(
            model_name='uploadedmedia',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='authorstyleprofile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorstyleprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='corrected_text',
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='reply_comment_id',
        ),
        migrations.AddField(
            model_name='authorstyleprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to='Visitor.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='commentmoderationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='commentmoderationlog',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='prompttemplate',
                    name='debug_script',
                    field=models.TextField(blank=True, default='', help_text='Используйте {переменные} для подстановки', null=True, verbose_name='Скрипт отладки'),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='AIFeedback',
        ),
        migrations.DeleteModel(
            name='PromptVersion',
        ),
        migrations.DeleteModel(
            name='TitleVariant',
        ),
        migrations.DeleteModel(
            name='UploadedMedia',
        ),
    ]
