# Generated by Django 5.1 on 2025-11-16 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0059_integrationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10, verbose_name='Уровень')),
                ('logger_name', models.CharField(db_index=True, help_text='Например: django, Asistent, django-q', max_length=100, verbose_name='Имя логгера')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('module', models.CharField(blank=True, db_index=True, help_text='Имя модуля где произошло событие', max_length=200, verbose_name='Модуль')),
                ('function', models.CharField(blank=True, help_text='Имя функции где произошло событие', max_length=200, verbose_name='Функция')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='ID процесса')),
                ('thread_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID потока')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация в формате JSON', verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': '📋 Системный лог',
                'verbose_name_plural': '📋 Системные логи',
                'db_table': 'asistent_systemlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='asistent_sy_timesta_2eaca1_idx'), models.Index(fields=['level', '-timestamp'], name='asistent_sy_level_dbb61e_idx'), models.Index(fields=['logger_name', '-timestamp'], name='asistent_sy_logger__56c5cf_idx'), models.Index(fields=['module', '-timestamp'], name='asistent_sy_module_519d3d_idx')],
            },
        ),
    ]
