# Generated by Django 5.0.8 on 2025-12-01 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_admin_field_if_missing(apps, schema_editor):
    """Добавляет поле admin_id, если его нет в таблице"""
    db = schema_editor.connection.alias
    
    # Проверяем, существует ли колонка admin_id
    with schema_editor.connection.cursor() as cursor:
        # Для MySQL
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'Asistent_aiconversation' 
            AND COLUMN_NAME = 'admin_id'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Получаем первого суперпользователя для значения по умолчанию
            cursor.execute("SELECT id FROM auth_user WHERE is_superuser = 1 LIMIT 1")
            result = cursor.fetchone()
            default_admin_id = result[0] if result else 1
            
            # Добавляем колонку как NULL сначала
            cursor.execute("""
                ALTER TABLE Asistent_aiconversation 
                ADD COLUMN admin_id INT NULL
            """)
            
            # Заполняем существующие записи
            cursor.execute(f"""
                UPDATE Asistent_aiconversation 
                SET admin_id = {default_admin_id} 
                WHERE admin_id IS NULL
            """)
            
            # Добавляем внешний ключ
            try:
                cursor.execute("""
                    ALTER TABLE Asistent_aiconversation 
                    ADD CONSTRAINT Asistent_aiconversation_admin_id_fk 
                    FOREIGN KEY (admin_id) REFERENCES auth_user(id) ON DELETE CASCADE
                """)
            except Exception as e:
                # Если внешний ключ уже существует, игнорируем
                pass
            
            # Делаем поле обязательным
            cursor.execute("""
                ALTER TABLE Asistent_aiconversation 
                MODIFY COLUMN admin_id INT NOT NULL
            """)


def reverse_migration(apps, schema_editor):
    """Откат миграции - удаляем поле admin_id"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'Asistent_aiconversation' 
            AND COLUMN_NAME = 'admin_id'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            # Удаляем внешний ключ (находим имя автоматически)
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM information_schema.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'Asistent_aiconversation' 
                AND COLUMN_NAME = 'admin_id' 
                AND REFERENCED_TABLE_NAME IS NOT NULL
                LIMIT 1
            """)
            fk_result = cursor.fetchone()
            if fk_result:
                fk_name = fk_result[0]
                cursor.execute(f"""
                    ALTER TABLE Asistent_aiconversation 
                    DROP FOREIGN KEY {fk_name}
                """)
            
            # Удаляем колонку
            cursor.execute("""
                ALTER TABLE Asistent_aiconversation 
                DROP COLUMN admin_id
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0065_add_pipeline_foreign_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_admin_field_if_missing, reverse_migration),
    ]
