# Generated by Django 5.0.8 on 2025-12-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0066_fix_aiconversation_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGenerationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало генерации')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение генерации')),
                ('total_duration', models.FloatField(blank=True, help_text='Время от начала до конца генерации', null=True, verbose_name='Общее время (сек)')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('context_build_duration', models.FloatField(blank=True, null=True, verbose_name='Построение контекста (сек)')),
                ('content_generation_duration', models.FloatField(blank=True, null=True, verbose_name='Генерация контента (сек)')),
                ('title_generation_duration', models.FloatField(blank=True, null=True, verbose_name='Генерация заголовка (сек)')),
                ('image_processing_duration', models.FloatField(blank=True, null=True, verbose_name='Обработка изображения (сек)')),
                ('tags_generation_duration', models.FloatField(blank=True, null=True, verbose_name='Генерация тегов (сек)')),
                ('content_length', models.IntegerField(blank=True, null=True, verbose_name='Длина контента (символов)')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='Количество слов')),
                ('tags_count', models.IntegerField(blank=True, null=True, verbose_name='Количество тегов')),
                ('has_image', models.BooleanField(default=False, verbose_name='Есть изображение')),
                ('image_source_type', models.CharField(blank=True, max_length=20, verbose_name='Тип источника изображения')),
                ('gigachat_model', models.CharField(blank=True, max_length=50, verbose_name='Модель GigaChat')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ID пользователя')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_metrics', to='Asistent.prompttemplate', verbose_name='Шаблон промпта')),
            ],
            options={
                'verbose_name': '📊 Метрика генерации статьи',
                'verbose_name_plural': '📊 Метрики генерации статей',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='Asistent_ar_started_f24d52_idx'), models.Index(fields=['template', '-started_at'], name='Asistent_ar_templat_107393_idx'), models.Index(fields=['success', '-started_at'], name='Asistent_ar_success_b7a33e_idx')],
            },
        ),
    ]
