# Generated by Django 5.0.8 on 2025-12-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0067_add_article_generation_metrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotFAQ',
        ),
        migrations.DeleteModel(
            name='ChatbotSettings',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
