# Generated by Django 5.0.8 on 2025-12-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0068_delete_chatbotfaq_delete_chatbotsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aischedule',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='aischedule',
            name='pipeline_slug',
        ),
        migrations.DeleteModel(
            name='PipelineRunLog',
        ),
        migrations.DeleteModel(
            name='AutomationPipeline',
        ),
    ]
