# Generated by Django 5.0.8 on 2025-12-03 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0069_remove_aischedule_pipeline_and_more'),
        ('blog', '0016_alter_like_unique_together_like_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Добавляем ForeignKey к Comment
        migrations.AddField(
            model_name='commentmoderationlog',
            name='comment',
            field=models.ForeignKey(
                default=1,  # Временное значение по умолчанию
                on_delete=django.db.models.deletion.CASCADE,
                related_name='moderation_logs',
                to='blog.comment',
                verbose_name='Комментарий',
            ),
            preserve_default=False,
        ),
        # Добавляем ForeignKey к CommentModerationCriteria
        migrations.AddField(
            model_name='commentmoderationlog',
            name='criteria',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='logs',
                to='Asistent.commentmoderationcriteria',
                verbose_name='Критерий',
            ),
        ),
        # Добавляем ForeignKey к User (moderator)
        migrations.AddField(
            model_name='commentmoderationlog',
            name='moderator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Модератор',
            ),
        ),
        # Обновляем choices для action_taken
        migrations.AlterField(
            model_name='commentmoderationlog',
            name='action_taken',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('delete', 'Удалить'),
                    ('correct', 'Исправить'),
                    ('reply', 'Ответить шаблоном'),
                    ('flag', 'Пометить для проверки'),
                ],
                verbose_name='Совершённое действие',
            ),
        ),
    ]
