# Generated by Django 5.0.8 on 2025-12-03 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0070_fix_commentmoderationlog_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной профиль', max_length=200, verbose_name='Название профиля')),
                ('is_active', models.BooleanField(default=True, help_text='Будет использоваться для проверки статей', verbose_name='Активен')),
                ('check_title', models.BooleanField(default=True, help_text='Заголовок не должен быть пустым', verbose_name='Проверять заголовок')),
                ('check_image', models.BooleanField(default=True, help_text='Статья должна содержать изображение', verbose_name='Проверять наличие изображения')),
                ('check_category', models.BooleanField(default=True, help_text='У статьи должна быть выбрана категория', verbose_name='Проверять категорию')),
                ('check_length', models.BooleanField(default=True, help_text='Проверять минимальное количество слов', verbose_name='Проверять длину текста')),
                ('check_profanity', models.BooleanField(default=False, help_text='Простая проверка на наличие матерных слов', verbose_name='Проверять мат')),
                ('min_words', models.IntegerField(default=300, help_text='Минимальное количество слов в статье', verbose_name='Минимум слов')),
                ('min_title_length', models.IntegerField(default=10, help_text='Минимальная длина заголовка', verbose_name='Минимум символов в заголовке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': '📝 Модерация: Настройки статей',
                'verbose_name_plural': '📝 Модерация: Настройки статей',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной профиль', max_length=200, verbose_name='Название профиля')),
                ('is_active', models.BooleanField(default=True, help_text='Будет использоваться для проверки комментариев', verbose_name='Активен')),
                ('block_urls', models.BooleanField(default=True, help_text='Запретить комментарии с http://, https://, www.', verbose_name='Блокировать ссылки')),
                ('block_html', models.BooleanField(default=True, help_text='Запретить комментарии с HTML-разметкой', verbose_name='Блокировать HTML-теги')),
                ('block_short', models.BooleanField(default=True, help_text='Запретить слишком короткие комментарии', verbose_name='Блокировать короткие')),
                ('check_spam', models.BooleanField(default=True, help_text='Простая проверка спам-слов', verbose_name='Проверять на спам')),
                ('min_length', models.IntegerField(default=10, help_text='Минимальная длина комментария', verbose_name='Минимум символов')),
                ('forbidden_words', models.TextField(blank=True, help_text='Список через запятую: купить, казино, спам, реклама', verbose_name='Запрещённые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': '💬 Модерация: Настройки комментариев',
                'verbose_name_plural': '💬 Модерация: Настройки комментариев',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentmoderationlog',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='criteria',
        ),
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '📋 Модерация: Журнал проверок', 'verbose_name_plural': '📋 Модерация: Журнал проверок'},
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='article',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='verdict',
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='content_type',
            field=models.CharField(choices=[('article', 'Статья'), ('comment', 'Комментарий')], default='article', max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Кто выполнил проверку (NULL = автомат)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='object_id',
            field=models.IntegerField(default=0, help_text='ID статьи или комментария', verbose_name='ID объекта'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='passed',
            field=models.BooleanField(default=False, help_text='True = пройдена, False = отклонена', verbose_name='Пройдена'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='problems',
            field=models.TextField(blank=True, help_text='Причины отклонения (по одной на строке)', verbose_name='Список проблем'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['-created_at'], name='Asistent_mo_created_0d91aa_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['content_type', 'object_id'], name='Asistent_mo_content_5aac59_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['passed'], name='Asistent_mo_passed_9cac9d_idx'),
        ),
        migrations.DeleteModel(
            name='CommentModerationCriteria',
        ),
        migrations.DeleteModel(
            name='CommentModerationLog',
        ),
        migrations.DeleteModel(
            name='ModerationCriteria',
        ),
    ]
