# Generated by Django 5.0.8 on 2025-12-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0071_articlemoderationsettings_commentmoderationsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleModerationSettings',
        ),
        migrations.DeleteModel(
            name='CommentModerationSettings',
        ),
        migrations.DeleteModel(
            name='ModerationLog',
        ),
    ]
