# Generated by Django 5.0.8 on 2025-12-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0072_delete_articlemoderationsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authornotification',
            options={'ordering': ['-created_at'], 'verbose_name': '📬 Уведомления для авторов', 'verbose_name_plural': '📬 Уведомления для авторов'},
        ),
    ]
