# Generated by Django 5.0.8
# Modified to safely handle missing tables and fields

import django.db.models.deletion
from django.db import migrations, models


def safely_remove_schedule_field(apps, schema_editor):
    """Безопасно удаляет поле schedule из AIScheduleRun, если таблица и поле существуют"""
    with schema_editor.connection.cursor() as cursor:
        # Сначала проверяем существование таблицы
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'Asistent_aischedulerun'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            print("Table Asistent_aischedulerun does not exist, skipping field removal")
            return
        
        # Проверяем наличие столбца schedule_id
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'Asistent_aischedulerun' 
            AND COLUMN_NAME = 'schedule_id'
        """)
        field_exists = cursor.fetchone()[0] > 0
        
        if field_exists:
            try:
                # Сначала удаляем внешний ключ, если он есть
                cursor.execute("""
                    SELECT CONSTRAINT_NAME 
                    FROM information_schema.KEY_COLUMN_USAGE 
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'Asistent_aischedulerun' 
                    AND COLUMN_NAME = 'schedule_id'
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                    LIMIT 1
                """)
                fk_result = cursor.fetchone()
                if fk_result:
                    fk_name = fk_result[0]
                    cursor.execute(f"ALTER TABLE Asistent_aischedulerun DROP FOREIGN KEY {fk_name}")
                    print(f"Dropped foreign key: {fk_name}")
                
                # Удаляем столбец
                cursor.execute("ALTER TABLE Asistent_aischedulerun DROP COLUMN schedule_id")
                print("Dropped column schedule_id from Asistent_aischedulerun")
            except Exception as e:
                print(f"Warning: Could not drop schedule_id column: {e}")
        else:
            print("Column schedule_id does not exist in Asistent_aischedulerun, skipping")


def safely_delete_table(apps, schema_editor, table_name):
    """Безопасно удаляет таблицу, если она существует, предварительно удаляя все внешние ключи"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = %s
        """, (table_name,))
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            try:
                # Сначала находим и удаляем все внешние ключи, которые ссылаются на эту таблицу
                cursor.execute("""
                    SELECT CONSTRAINT_NAME, TABLE_NAME
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND REFERENCED_TABLE_NAME = %s
                """, (table_name,))
                
                foreign_keys = cursor.fetchall()
                for fk_name, fk_table in foreign_keys:
                    try:
                        cursor.execute(f"ALTER TABLE {fk_table} DROP FOREIGN KEY {fk_name}")
                        print(f"Dropped foreign key {fk_name} from {fk_table}")
                    except Exception as e:
                        print(f"Warning: Could not drop foreign key {fk_name} from {fk_table}: {e}")
                
                # Теперь удаляем саму таблицу
                cursor.execute(f"DROP TABLE {table_name}")
                print(f"Dropped table: {table_name}")
            except Exception as e:
                print(f"Warning: Could not drop table {table_name}: {e}")
        else:
            print(f"Table {table_name} does not exist, skipping")


def remove_aischedulerun_schedule_field(apps, schema_editor):
    """Удаляет поле schedule из AIScheduleRun"""
    safely_remove_schedule_field(apps, schema_editor)


def delete_aischedule_table(apps, schema_editor):
    """Удаляет таблицу AISchedule"""
    safely_delete_table(apps, schema_editor, 'Asistent_aischedule')


def delete_aischedulerun_table(apps, schema_editor):
    """Удаляет таблицу AIScheduleRun"""
    safely_delete_table(apps, schema_editor, 'Asistent_aischedulerun')


def reverse_operations(apps, schema_editor):
    """Откат операций (не восстанавливаем удалённые таблицы)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0074_alter_aigeneratedarticle_schedule_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_aischedulerun_schedule_field,
            reverse_operations,
        ),
        migrations.RunPython(
            delete_aischedule_table,
            reverse_operations,
        ),
        migrations.RunPython(
            delete_aischedulerun_table,
            reverse_operations,
        ),
    ]

