# Generated by Django 5.1 on 2026-02-12 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0075_remove_aischedulerun_schedule_delete_aischedule_and_more'),
    ]

    operations = [
        # Только обновляем состояние миграций: таблицы AISchedule/AIScheduleRun
        # используются Asistent.schedule (db_table=Asistent_aischedule), в БД не трогаем.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='aischedulerun',
                    name='schedule',
                ),
                migrations.DeleteModel(name='AISchedule'),
                migrations.DeleteModel(name='AIScheduleRun'),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='alert_threshold_percent',
            field=models.IntegerField(default=20, help_text='Только для отображения в Dashboard', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог алерта (%)'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='auto_switch_enabled',
            field=models.BooleanField(default=True, help_text='[УСТАРЕЛО] Не используется - переключения отключены', verbose_name='Автопереключение моделей'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='check_balance_after_requests',
            field=models.IntegerField(default=1, help_text='[УСТАРЕЛО] Только для ручной проверки в дашборде', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Проверять баланс после N запросов'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='current_model',
            field=models.CharField(default='GigaChat', help_text='[УСТАРЕЛО] Только для отображения, не используется в логике', max_length=50, verbose_name='Текущая модель'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='lite_daily_limit',
            field=models.IntegerField(default=2000000, help_text='[УСТАРЕЛО] Не используется - проверки лимитов отключены', verbose_name='Дневной лимит Lite (токены)'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='max_daily_limit',
            field=models.IntegerField(default=500000, help_text='[УСТАРЕЛО] Не используется - проверки лимитов отключены', verbose_name='Дневной лимит Max (токены)'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='models_priority',
            field=models.JSONField(default=list, help_text='[УСТАРЕЛО] Только для отображения', verbose_name='Приоритет моделей'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='preventive_switch_threshold',
            field=models.IntegerField(default=10, help_text='[УСТАРЕЛО] Не используется - переключения отключены', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог превентивного переключения (%)'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='pro_daily_limit',
            field=models.IntegerField(default=1000000, help_text='[УСТАРЕЛО] Не используется - проверки лимитов отключены', verbose_name='Дневной лимит Pro (токены)'),
        ),
        migrations.AlterField(
            model_name='gigachatsettings',
            name='request_counter',
            field=models.IntegerField(default=0, help_text='[УСТАРЕЛО] Не используется', verbose_name='Счётчик запросов'),
        ),
    ]
