# Generated by Django 5.1 on 2026-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asistent", "0076_remove_aischedulerun_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="logger_name",
            field=models.CharField(
                db_index=True,
                help_text="Например: django, Asistent, celery",
                max_length=100,
                verbose_name="Имя логгера",
            ),
        ),
    ]
