# Generated by Django 5.1 on 2024-08-18 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Опубликованно в Телеге'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kartinka',
            field=models.FileField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif', 'mp4'))], verbose_name='Превью поста'),
        ),
    ]
