# Generated by Django 5.0.8 on 2024-08-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_description_alter_post_fixed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
