# Generated by Django 5.0.8 on 2024-08-24 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='app_comment_created_b8363d_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='time_update',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-time_create', 'time_update', 'status', 'parent'], name='app_comment_time_cr_0c0ec5_idx'),
        ),
    ]
