# Generated by Django 5.0.8 on 2024-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_description_alter_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='app_comment_time_cr_0c0ec5_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_update',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_comment',
            field=models.CharField(default=1, max_length=80, verbose_name='Автор комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created', 'updated', 'active'], name='app_comment_created_e5b4a7_idx'),
        ),
    ]
