# Generated by Django 5.0.8 on 2024-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kartinka',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Превью поста'),
        ),
    ]
