# Generated by Django 5.0.8 on 2024-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_kartinka'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id канала'),
        ),
        migrations.AddField(
            model_name='category',
            name='chat_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='url канала'),
        ),
        migrations.AddField(
            model_name='category',
            name='kartinka',
            field=models.FileField(blank=True, upload_to='Telega/', verbose_name='картинка телеграмма'),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
