# Generated by Django 5.1 on 2025-09-29 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_category_chat_id_category_chat_url_category_kartinka_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Полное описание"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="fixed",
            field=models.BooleanField(default=False, verbose_name="ФИКСА"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("published", "Опубликовано"), ("draft", "Черновик")],
                default="draft",
                max_length=10,
                verbose_name="Статус поста",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="telegram_posted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Опубликованно в Телеграмме"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0, verbose_name="просмотров"),
        ),
    ]
