# Generated by Django 5.2.7 on 2025-10-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0001_initial'),
        ('blog', '0015_add_ai_moderation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ai_moderation_notes',
            field=models.TextField(blank=True, verbose_name='Замечания AI'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_articles', to='Asistent.contenttask', verbose_name='Связанное задание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации AI'), ('approved', 'Одобрено AI'), ('rejected', 'Отклонено AI'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус модерации AI'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'session_key'], name='app_likes_post_id_69fc49_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('post', 'session_key'), name='unique_like_per_session'),
        ),
    ]
