# Generated by Django 5.2.7 on 2025-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_like_unique_together_like_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(
                blank=True,
                max_length=60,
                verbose_name='SEO заголовок',
                help_text='Оптимизированный заголовок для поисковиков (до 60 символов)'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(
                blank=True,
                max_length=160,
                verbose_name='SEO описание',
                help_text='Краткое описание для поисковиков (до 160 символов)'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(
                blank=True,
                max_length=95,
                verbose_name='OG заголовок',
                help_text='Заголовок для социальных сетей (Facebook, VK)'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.TextField(
                blank=True,
                max_length=200,
                verbose_name='OG описание',
                help_text='Описание для социальных сетей'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name='Ключевое слово',
                help_text='Главное ключевое слово для SEO'
            ),
        ),
    ]
