# Generated by Django 5.2.7 on 2025-10-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_add_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_draft_improved',
            field=models.TextField(blank=True, help_text='Версия текста после улучшения AI', verbose_name='Улучшенная версия'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_draft_improvement_requested',
            field=models.BooleanField(default=False, help_text='Автор запросил AI помочь с улучшением черновика', verbose_name='Запрошено улучшение AI'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_draft_original',
            field=models.TextField(blank=True, help_text='Версия текста до улучшения AI', verbose_name='Оригинальный черновик'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_improvement_notes',
            field=models.TextField(blank=True, help_text='Что именно улучшил AI', verbose_name='Заметки AI об улучшениях'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_improvement_status',
            field=models.CharField(blank=True, choices=[('pending', 'В обработке'), ('ready', 'Готово к проверке'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Статус улучшения AI'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_improvement_style',
            field=models.CharField(blank=True, choices=[('literary', 'Литературный'), ('seo', 'SEO-оптимизированный'), ('emotional', 'Эмоциональный'), ('balanced', 'Сбалансированный')], max_length=20, verbose_name='Стиль улучшения AI'),
        ),
        migrations.AlterField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Основное ключевое слово для SEO', max_length=100, verbose_name='Главное ключевое слово'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковиков (до 160 символов)', max_length=160, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_description',
            field=models.CharField(blank=True, help_text='Описание для соцсетей (до 160 символов)', max_length=160, verbose_name='Open Graph описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, help_text='Заголовок для соцсетей (до 60 символов)', max_length=60, verbose_name='Open Graph заголовок'),
        ),
    ]
