# Generated by Django 5.2.7 on 2025-10-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_ai_draft_improved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_video',
            field=models.URLField(blank=True, help_text='URL видео с YouTube, Vimeo или прямая ссылка на .mp4', null=True, verbose_name='Видео превью (URL)'),
        ),
        migrations.AddField(
            model_name='post',
            name='prefer_video',
            field=models.BooleanField(default=False, help_text='Если TRUE и есть видео - показывать его вместо картинки', verbose_name='Показывать видео вместо изображения'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.FileField(blank=True, help_text='Превью для видео (если есть)', null=True, upload_to='video_thumbnails/', verbose_name='Превью видео (изображение)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kartinka',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Превью поста (изображение)'),
        ),
    ]
