# Generated by Django 5.2.7 on 2025-10-12 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_add_video_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео файл (.mp4, .webm, .mov, .avi)', null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi'])], verbose_name='Видео файл (загрузить)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_video',
            field=models.URLField(blank=True, help_text='URL видео с YouTube, Vimeo или прямая ссылка. Если загружен файл - это поле игнорируется.', null=True, verbose_name='Видео URL (или вставить ссылку)'),
        ),
    ]
