# Generated by Django 5.2.7 on 2025-10-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_add_video_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_video_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='prefer_video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Если не удается загрузить видео - укажите ссылку (приоритет над изображением)', verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kartinka',
            field=models.FileField(blank=True, help_text='Загрузите изображение или видео (mp4, webm, mov)', upload_to='images/', verbose_name='Превью поста (изображение/видео)'),
        ),
    ]
