# Generated by Django 5.1 on 2025-10-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Старый URL')),
                ('new_url', models.CharField(blank=True, help_text='Если пусто - возвращается 410 Gone', max_length=500, verbose_name='Новый URL (редирект)')),
                ('redirect_type', models.IntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary'), (410, '410 Gone')], default=301, verbose_name='Тип редиректа')),
                ('hits_count', models.IntegerField(default=0, verbose_name='Количество обращений')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первое обращение')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последнее обращение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Редирект URL',
                'verbose_name_plural': 'Редиректы URL',
                'db_table': 'app_url_redirects',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['old_url'], name='app_url_red_old_url_0edf22_idx'), models.Index(fields=['-hits_count'], name='app_url_red_hits_co_cb709a_idx')],
            },
        ),
    ]
