# Generated by Django 5.1 on 2025-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_urlredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_publish_social',
            field=models.BooleanField(default=True, help_text='Автоматически публиковать при статусе "Опубликовано"', verbose_name='Автопубликация в соцсетях'),
        ),
        migrations.AddField(
            model_name='post',
            name='social_platforms',
            field=models.JSONField(blank=True, default=list, help_text='["telegram", "vk", "pinterest", "rutube", "dzen"]', verbose_name='Платформы для публикации'),
        ),
    ]
