# Generated by Django 5.1 on 2025-10-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_auto_publish_social_post_social_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kartinka',
            field=models.FileField(blank=True, max_length=500, upload_to='Telega/', verbose_name='картинка телеграмма'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kartinka',
            field=models.FileField(blank=True, help_text='Загрузите изображение или видео (mp4, webm, mov)', max_length=500, upload_to='images/', verbose_name='Превью поста (изображение/видео)'),
        ),
    ]
