# Generated by Django 5.1 on 2025-10-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_extend_kartinka_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_help_image',
            field=models.BooleanField(default=False, help_text='AI автоматически нашел и добавил изображение (-30% баллов)', verbose_name='AI подобрал изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_help_profanity',
            field=models.BooleanField(default=False, help_text='AI удалил ненормативную лексику (-30% баллов)', verbose_name='AI убрал мат'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_help_text',
            field=models.BooleanField(default=False, help_text='AI дополнил статью до минимума (-30% баллов)', verbose_name='AI дополнил текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_penalty_percent',
            field=models.IntegerField(default=0, help_text='Общий процент штрафа за помощь AI', verbose_name='Штраф от AI (%)'),
        ),
    ]
