# Generated by Django 5.1 on 2025-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_add_ai_help_penalty_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_help_uniqueness',
            field=models.BooleanField(default=False, help_text='AI переписал статью для уникальности (-10% баллов)', verbose_name='AI переделал текст для уникальности'),
        ),
    ]
