# Generated by Django 5.0.8 on 2025-12-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_ai_improvement_task_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_preview',
            field=models.ImageField(blank=True, help_text='Автоматически генерируется из основного изображения для соцсетей', null=True, upload_to='og_previews/', verbose_name='OG-превью (1200x630px)'),
        ),
    ]
