# Generated by Django 5.0.8 on 2025-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_add_og_preview_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Автоматически определяется при обработке', null=True, verbose_name='Длительность видео (секунды)'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_optimized',
            field=models.BooleanField(default=False, help_text='Автоматически устанавливается после оптимизации видео', verbose_name='Видео оптимизировано'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Автоматически создается из первого кадра видео', null=True, upload_to='video_posters/', verbose_name='Poster изображение для видео'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус обработки видео'),
        ),
    ]
