# Generated by Django 5.0.8 on 2025-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_add_video_optimization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Автоматически создается из основного изображения для быстрой загрузки в списках (600x400 WebP)', null=True, upload_to='thumbnails/', verbose_name='Thumbnail изображение'),
        ),
    ]
