# Generated by Django 5.1 on 2026-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_add_thumbnail_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_preview",
            field=models.FileField(
                blank=True,
                help_text="Автоматически создается 5-секундный ролик низкого качества для автоплея",
                null=True,
                upload_to="video_previews/",
                verbose_name="Короткое превью (5 сек)",
            ),
        ),
    ]
