# Generated by Django 5.2.7 on 2025-10-08 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Минимальная сумма')),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000, max_digits=10, verbose_name='Максимальная сумма')),
                ('preset_amounts', models.JSONField(default=list, help_text='Например: [100, 500, 1000, 5000]', verbose_name='Предустановленные суммы')),
                ('enable_yandex', models.BooleanField(default=True, verbose_name='Включить Яндекс.Кассу')),
                ('enable_sberpay', models.BooleanField(default=True, verbose_name='Включить СберПей')),
                ('enable_sbp', models.BooleanField(default=True, verbose_name='Включить СБП')),
                ('enable_qr', models.BooleanField(default=True, verbose_name='Включить QR-код')),
                ('send_email_to_donor', models.BooleanField(default=True, verbose_name='Отправлять email донатеру')),
                ('send_email_to_admin', models.BooleanField(default=True, verbose_name='Отправлять email администратору')),
                ('admin_emails', models.TextField(blank=True, help_text='По одному на строку', verbose_name='Email администраторов')),
                ('thank_you_subject', models.CharField(default='Спасибо за ваш донат!', max_length=255, verbose_name='Тема благодарственного письма')),
                ('thank_you_message', models.TextField(default='Большое спасибо за вашу поддержку! Ваш донат помогает нам развиваться.', verbose_name='Текст благодарственного письма')),
                ('donation_page_title', models.CharField(default='Поддержать проект', max_length=255, verbose_name='Заголовок страницы донатов')),
                ('donation_page_description', models.TextField(default='Ваша поддержка помогает нам развивать проект и создавать качественный контент.', verbose_name='Описание на странице донатов')),
            ],
            options={
                'verbose_name': 'Настройки донатов',
                'verbose_name_plural': 'Настройки донатов',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Для отправки благодарственного письма', max_length=254, verbose_name='Email донатера')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Имя донатера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('payment_method', models.CharField(choices=[('yandex', 'Яндекс.Касса'), ('sberpay', 'СберПей'), ('sbp', 'Система Быстрых Платежей'), ('qr', 'QR-код')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидание оплаты'), ('processing', 'В обработке'), ('succeeded', 'Успешно'), ('canceled', 'Отменено'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа в платежной системе')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('message', models.TextField(blank=True, help_text='Пожелания или комментарий', verbose_name='Сообщение от донатера')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный донат')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='Base64 QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='Данные платежа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email_donor', 'Email донатеру'), ('email_admin', 'Email администратору'), ('telegram', 'Telegram уведомление')], max_length=20)),
                ('recipient', models.CharField(max_length=255, verbose_name='Получатель')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_system', models.CharField(max_length=50, verbose_name='Платежная система')),
                ('webhook_data', models.JSONField(verbose_name='Данные webhook')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Webhook лог',
                'verbose_name_plural': 'Webhook логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-created_at'], name='donations_d_created_7012d0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_id'], name='donations_d_payment_47937a_idx'),
        ),
    ]
