# Generated by Django 5.1 on 2025-10-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistent', '0001_initial'),
        ('blog', '0022_add_performance_indexes'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBonusCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('update_formula', 'Обновить формулу'), ('add_penalty', 'Добавить штраф'), ('add_reward', 'Добавить премию'), ('adjust_bonus', 'Скорректировать бонус'), ('change_role_percentage', 'Изменить процент роли')], max_length=50, verbose_name='Тип команды')),
                ('parameters', models.JSONField(default=dict, help_text='JSON с параметрами для выполнения команды', verbose_name='Параметры команды')),
                ('executed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('result', models.JSONField(default=dict, help_text='Результат или ошибка выполнения', verbose_name='Результат выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '🤖 AI: Команда по бонусам',
                'verbose_name_plural': '🤖 AI: Команды по бонусам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('donations_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма донатов за статьи автора', max_digits=10, verbose_name='Сумма донатов')),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент бонуса')),
                ('calculated_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Рассчитанный бонус в рублях из донатов', max_digits=10, verbose_name='Бонус от донатов')),
                ('tasks_reward', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вознаграждение за задания')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработанные баллы')),
                ('point_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Стоимость балла')),
                ('bonus_from_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус из баллов')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, help_text='donations + tasks + points', max_digits=10, verbose_name='Общий бонус')),
                ('status', models.CharField(choices=[('pending', 'Ожидает утверждения'), ('approved', 'Утверждено'), ('paid', 'Выплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Начисление',
                'verbose_name_plural': '💰 Бонусы: Начисления',
                'ordering': ['-period_start', 'author'],
            },
        ),
        migrations.CreateModel(
            name='AuthorPenaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penalty', 'Штраф'), ('reward', 'Премия')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма в рублях или процентах', max_digits=10, verbose_name='Сумма')),
                ('amount_type', models.CharField(choices=[('fixed', 'Фиксированная сумма'), ('percentage', 'Процент от бонуса')], max_length=20, verbose_name='Тип суммы')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('applied_to', models.CharField(choices=[('one_time', 'Разовый'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный')], default='one_time', max_length=20, verbose_name='Применение')),
                ('applied_from', models.DateTimeField(verbose_name='Действует с')),
                ('applied_until', models.DateTimeField(blank=True, help_text='Оставьте пустым для бессрочного', null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Штраф/Премия',
                'verbose_name_plural': '💰 Бонусы: Штрафы и премии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Стажёр, Автор, Писатель, Бестселлер', max_length=100, unique=True, verbose_name='Название роли')),
                ('level', models.IntegerField(help_text='1-4, где 1 - самый низкий', unique=True, verbose_name='Уровень роли')),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Процент от донатов за статьи автора (по умолчанию)', max_digits=5, verbose_name='Процент от донатов')),
                ('point_value', models.DecimalField(decimal_places=2, default=1.0, help_text='Сколько рублей стоит один балл для этой роли', max_digits=10, verbose_name='Стоимость балла')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('color', models.CharField(default='#6B7280', help_text='Цвет для отображения роли (HEX)', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Роль автора',
                'verbose_name_plural': '💰 Бонусы: Роли авторов',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='AuthorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('all_time', 'Всё время')], max_length=20, verbose_name='Тип периода')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('articles_count', models.IntegerField(default=0, verbose_name='Количество статей')),
                ('total_likes', models.IntegerField(default=0, verbose_name='Всего лайков')),
                ('total_comments', models.IntegerField(default=0, verbose_name='Всего комментариев')),
                ('total_views', models.IntegerField(default=0, verbose_name='Всего просмотров')),
                ('completed_tasks_count', models.IntegerField(default=0, verbose_name='Выполнено заданий')),
                ('tasks_reward_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вознаграждение за задания')),
                ('calculated_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рассчитанные баллы')),
                ('articles_detail', models.JSONField(default=list, help_text='Список статей с лайками, комментариями, просмотрами', verbose_name='Детали по статьям')),
                ('tasks_detail', models.JSONField(default=list, help_text='Список выполненных заданий с вознаграждениями', verbose_name='Детали по заданиям')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата расчета')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Статистика автора',
                'verbose_name_plural': '💰 Бонусы: Статистика авторов',
                'ordering': ['-period_start', 'author'],
            },
        ),
        migrations.CreateModel(
            name='BonusFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Сколько баллов за одну опубликованную статью', max_digits=10, verbose_name='Вес статьи')),
                ('likes_weight', models.DecimalField(decimal_places=2, default=0.5, help_text='Сколько баллов за один лайк', max_digits=10, verbose_name='Вес лайка')),
                ('comments_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Сколько баллов за один комментарий', max_digits=10, verbose_name='Вес комментария')),
                ('views_weight', models.DecimalField(decimal_places=4, default=0.01, help_text='Сколько баллов за один просмотр', max_digits=10, verbose_name='Вес просмотра')),
                ('tasks_weight', models.DecimalField(decimal_places=2, default=5.0, help_text='Сколько баллов за одно выполненное задание', max_digits=10, verbose_name='Вес выполненного задания')),
                ('min_points_required', models.DecimalField(decimal_places=2, default=0, help_text='Минимум баллов за неделю для получения этой роли', max_digits=10, verbose_name='Минимум баллов')),
                ('min_articles_required', models.IntegerField(default=0, help_text='Минимум статей за неделю (опционально)', verbose_name='Минимум статей')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли эта формула', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Формула расчета',
                'verbose_name_plural': '💰 Бонусы: Формулы расчета',
            },
        ),
        migrations.CreateModel(
            name='BonusPaymentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выплате')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплаченная сумма')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('payment_method', models.CharField(blank=True, help_text='Карта, наличные, и т.д.', max_length=100, verbose_name='Способ выплаты')),
                ('payment_note', models.TextField(blank=True, verbose_name='Примечание к оплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Реестр выплат',
                'verbose_name_plural': '💰 Бонусы: Реестр выплат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField(verbose_name='Начало недели')),
                ('week_end', models.DateTimeField(verbose_name='Конец недели')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('report_data', models.JSONField(default=dict, help_text='JSON с данными всех авторов', verbose_name='Данные отчета')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма донатов')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма бонусов')),
                ('total_tasks_rewards', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма за задания')),
                ('authors_count', models.IntegerField(default=0, verbose_name='Количество авторов')),
                ('is_finalized', models.BooleanField(default=False, help_text='После фиксации отчет нельзя изменить', verbose_name='Зафиксирован')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата фиксации')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': '💰 Бонусы: Недельный отчет',
                'verbose_name_plural': '💰 Бонусы: Недельные отчеты',
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Статья, через которую сделан донат', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blog.post', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='donation',
            name='article_author',
            field=models.ForeignKey(blank=True, help_text='Автор статьи (копируется из статьи при создании доната)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['article'], name='donations_d_article_411c43_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['article_author'], name='donations_d_article_c966bd_idx'),
        ),
        migrations.AddField(
            model_name='aibonuscommand',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_commands', to='Asistent.aiconversation', verbose_name='Диалог'),
        ),
        migrations.AddField(
            model_name='aibonuscommand',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_commands', to='Asistent.aimessage', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='aibonuscommand',
            name='target_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_bonus_commands', to=settings.AUTH_USER_MODEL, verbose_name='Целевой автор'),
        ),
        migrations.AddField(
            model_name='authorbonus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='authorpenaltyreward',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='authorpenaltyreward',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='authorbonus',
            name='role_at_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.authorrole', verbose_name='Роль при расчете'),
        ),
        migrations.AddField(
            model_name='authorstats',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_stats', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='authorstats',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_stats', to='donations.authorrole', verbose_name='Текущая роль'),
        ),
        migrations.AddField(
            model_name='bonusformula',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='donations.authorrole', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='bonuspaymentregistry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_registry', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='bonuspaymentregistry',
            name='bonus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='donations.authorbonus', verbose_name='Начисление бонуса'),
        ),
        migrations.AddField(
            model_name='bonuspaymentregistry',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_payments', to=settings.AUTH_USER_MODEL, verbose_name='Отметил оплату'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reports', to=settings.AUTH_USER_MODEL, verbose_name='Зафиксировал'),
        ),
        migrations.AddField(
            model_name='bonuspaymentregistry',
            name='week_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_registry', to='donations.weeklyreport', verbose_name='Недельный отчет'),
        ),
        migrations.AddIndex(
            model_name='aibonuscommand',
            index=models.Index(fields=['conversation', '-created_at'], name='donations_a_convers_87b364_idx'),
        ),
        migrations.AddIndex(
            model_name='aibonuscommand',
            index=models.Index(fields=['executed'], name='donations_a_execute_e51f34_idx'),
        ),
        migrations.AddIndex(
            model_name='authorpenaltyreward',
            index=models.Index(fields=['author', 'is_active'], name='donations_a_author__24d7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='authorpenaltyreward',
            index=models.Index(fields=['applied_from', 'applied_until'], name='donations_a_applied_6b2e03_idx'),
        ),
        migrations.AddIndex(
            model_name='authorbonus',
            index=models.Index(fields=['author', '-period_start'], name='donations_a_author__375c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='authorbonus',
            index=models.Index(fields=['status'], name='donations_a_status_32e2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='authorstats',
            index=models.Index(fields=['author', '-period_start'], name='donations_a_author__5d58aa_idx'),
        ),
        migrations.AddIndex(
            model_name='authorstats',
            index=models.Index(fields=['period_type', '-period_start'], name='donations_a_period__9bf9d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authorstats',
            unique_together={('author', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['-week_start'], name='donations_w_week_st_c0b14b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['is_finalized'], name='donations_w_is_fina_f38ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuspaymentregistry',
            index=models.Index(fields=['week_report', 'author'], name='donations_b_week_re_8762fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuspaymentregistry',
            index=models.Index(fields=['status'], name='donations_b_status_fa542c_idx'),
        ),
    ]
