# Generated by Django 5.1 on 2025-10-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_add_performance_indexes'),
        ('donations', '0002_aibonuscommand_authorbonus_authorpenaltyreward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
            ],
            options={
                'verbose_name': 'Покупка статьи',
                'verbose_name_plural': 'Покупки статей',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_days', models.IntegerField(verbose_name='Длительность (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Марафон',
                'verbose_name_plural': 'Марафоны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarathonPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
            ],
            options={
                'verbose_name': 'Покупка марафона',
                'verbose_name_plural': 'Покупки марафонов',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PaidArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платная статья',
                'verbose_name_plural': 'Платные статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('premium', 'Premium (без рекламы)'), ('ai_coauthor', 'AI-Соавтор')], max_length=20, verbose_name='Тип подписки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_created_7012d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_status_73ca83_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_payment_47937a_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_article_411c43_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_article_c966bd_idx',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_purpose',
            field=models.CharField(choices=[('donation', 'Донат'), ('premium_monthly', 'Premium подписка (месяц)'), ('premium_3months', 'Premium подписка (3 месяца)'), ('premium_yearly', 'Premium подписка (год)'), ('ai_coauthor_monthly', 'AI-Соавтор (месяц)'), ('ai_once', 'AI-Соавтор (разово)'), ('ai_pack_5', 'AI-Соавтор (пакет 5 статей)'), ('ai_pack_10', 'AI-Соавтор (пакет 10 статей)'), ('ai_pack_30', 'AI-Соавтор (пакет 30 статей)'), ('marathon_skin', 'Марафон: Идеальная кожа'), ('marathon_makeup', 'Марафон: Макияж'), ('marathon_wardrobe', 'Марафон: Капсульный гардероб'), ('ad_main_banner', 'Реклама: Баннер на главной'), ('ad_sidebar', 'Реклама: Боковой блок'), ('ad_in_content', 'Реклама: Внутри статей'), ('ad_article', 'Реклама: Рекламная статья'), ('ad_ticker', 'Реклама: Бегущая строка'), ('ad_telegram', 'Реклама: Посты в Telegram'), ('ad_pack_start', 'Реклама: Пакет Старт'), ('ad_pack_pro', 'Реклама: Пакет Профи')], default='donation', max_length=30, verbose_name='Назначение платежа'),
        ),
        migrations.AddField(
            model_name='articlepurchase',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donation', verbose_name='Платеж'),
        ),
        migrations.AddField(
            model_name='articlepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='articles',
            field=models.ManyToManyField(blank=True, to='blog.post', verbose_name='Статьи марафона'),
        ),
        migrations.AddField(
            model_name='marathonpurchase',
            name='marathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.marathon', verbose_name='Марафон'),
        ),
        migrations.AddField(
            model_name='marathonpurchase',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donation', verbose_name='Платеж'),
        ),
        migrations.AddField(
            model_name='marathonpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='paidarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_access', to='blog.post', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articlepurchase',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.paidarticle', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donation', verbose_name='Платеж'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='marathonpurchase',
            unique_together={('user', 'marathon')},
        ),
        migrations.AlterUniqueTogether(
            name='articlepurchase',
            unique_together={('user', 'article')},
        ),
    ]
