# Generated by Django 5.2.7 on 2025-10-11 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', '🎯 Hero секция'), ('features', '💎 Уникальность контента'), ('technology', '🚀 Технологии AI'), ('categories', '🔥 Популярные категории'), ('blogger', '✍️ Станьте блогером'), ('advertising', '💣 Реклама'), ('top_posts', '🏆 Лучшие статьи'), ('network', '🌐 Сеть порталов'), ('cta', '🎯 Call to Action')], help_text='Выберите секцию лендинга', max_length=50, unique=True, verbose_name='Секция')),
                ('media_type', models.CharField(choices=[('none', 'Без фона'), ('image', 'Изображение'), ('video', 'Видео'), ('gradient', 'Градиент')], default='gradient', max_length=20, verbose_name='Тип медиа')),
                ('background_image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920x1080px', null=True, upload_to='landing/backgrounds/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Фоновое изображение')),
                ('background_video', models.FileField(blank=True, help_text='Рекомендуемый формат: MP4, макс. 10MB', null=True, upload_to='landing/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='Фоновое видео')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на embed видео с Rutube, VK, YouTube и т.д.', null=True, verbose_name='URL видео (embed)')),
                ('gradient_colors', models.CharField(blank=True, default='from-pink-500 via-purple-500 to-indigo-600', help_text='Tailwind CSS классы градиента, например: from-blue-500 to-purple-600', max_length=200, verbose_name='Цвета градиента')),
                ('opacity', models.IntegerField(default=90, help_text='От 0 до 100', verbose_name='Прозрачность фона (%)')),
                ('overlay_color', models.CharField(blank=True, default='black', help_text='Цвет затемнения/осветления поверх фона', max_length=50, verbose_name='Цвет наложения')),
                ('overlay_opacity', models.IntegerField(default=0, help_text='От 0 до 100', verbose_name='Прозрачность наложения (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать этот фон для секции', verbose_name='Активно')),
                ('ai_generated', models.BooleanField(default=False, help_text='Медиафайл подобран автоматически AI-ассистентом', verbose_name='Создано AI')),
                ('ai_search_query', models.CharField(blank=True, help_text='Поисковый запрос, использованный AI для подбора контента', max_length=200, verbose_name='Запрос для AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Секция лендинга',
                'verbose_name_plural': 'Секции лендинга',
                'ordering': ['section'],
            },
        ),
    ]
