# Generated by Django 5.2.7 on 2025-10-11 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Лето 2025", "Мода и стиль", "Минимализм"', max_length=200, verbose_name='Название темы')),
                ('style_prompt', models.TextField(help_text='Описание стиля, который использовался для генерации (например: "яркие летние цвета, пляж, солнце")', verbose_name='Стиль/Запрос для AI')),
                ('is_active', models.BooleanField(default=False, help_text='Тема, которая сейчас применена к лендингу', verbose_name='Активная тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sections_config', models.JSONField(default=dict, help_text='JSON с настройками всех секций лендинга', verbose_name='Конфигурация секций')),
                ('preview_image', models.ImageField(blank=True, help_text='Скриншот или превью темы', null=True, upload_to='landing/themes/previews/', verbose_name='Превью темы')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Тема лендинга',
                'verbose_name_plural': 'Темы лендинга',
                'ordering': ['-created_at'],
            },
        ),
    ]
