# Generated by Django 5.2.7 on 2025-10-12 07:27

import Home.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_landingtheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920x1080px, макс 2MB (автоматически оптимизируется)', null=True, upload_to='landing/backgrounds/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), Home.models.validate_image_size], verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='background_video',
            field=models.FileField(blank=True, help_text='Рекомендуемый формат: MP4, макс 10MB (используйте сжатие!)', null=True, upload_to='landing/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg']), Home.models.validate_video_size], verbose_name='Фоновое видео'),
        ),
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_landing', models.CharField(choices=[('landing1', '🎨 Лендинг №1 (Оригинальный IdealImage)'), ('landing2', '💅 Лендинг №2 (Салон красоты)')], default='landing1', help_text='Выберите лендинг, который будет отображаться на главной странице', max_length=20, verbose_name='Активный лендинг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Настройка главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
    ]
