# Generated by Django 5.2.7 on 2025-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_landingsection_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsection',
            name='section',
            field=models.CharField(choices=[('hero', '🎯 Hero секция'), ('features', '💎 Уникальность контента + AI Технологии (объединённая)'), ('categories', '🔥 Популярные категории'), ('blogger', '✍️ Станьте блогером'), ('advertising', '💣 Реклама'), ('top_posts', '🏆 Лучшие статьи'), ('network', '🌐 Сеть порталов'), ('cta', '🎯 Call to Action')], help_text='Выберите секцию лендинга', max_length=50, unique=True, verbose_name='Секция'),
        ),
    ]
