# Generated by Django 5.2.7 on 2025-10-12 14:11

import Home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_landingsection_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "IdealImage.ru", "BeautyStyle.ru"', max_length=100, verbose_name='Название портала')),
                ('description', models.CharField(help_text='Краткое описание портала', max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 400x300px, макс 2MB', upload_to='landing/portals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), Home.models.validate_image_size], verbose_name='Изображение портала')),
                ('url', models.URLField(help_text='Полный URL портала (например: https://idealimage.ru)', verbose_name='Ссылка на портал')),
                ('is_main', models.BooleanField(default=False, help_text='Выделить как главный портал (специальная рамка)', verbose_name='Главный портал')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать на лендинге', verbose_name='Активен')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Портал',
                'verbose_name_plural': '🌐 Порталы (Сеть)',
                'ordering': ['order', 'name'],
            },
        ),
    ]
