# Generated by Django 5.2.7 on 2025-10-12 14:14

import Home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_add_portal_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 400x300px, макс 2MB', null=True, upload_to='landing/portals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), Home.models.validate_image_size], verbose_name='Изображение портала'),
        ),
    ]
