# Generated by Django 5.1 on 2026-03-17 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Зависимость от 0073, а не 0078, чтобы избежать цикла: 0074 зависит от schedule.__first__
        ("Asistent", "0073_alter_authornotification_options"),
        ("blog", "0032_post_video_preview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название расписания"
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Промпт-шаблон"),
                            ("system", "Системная задача"),
                            ("manual", "Ручной режим"),
                            ("pipeline", "Пайплайн автоматизации"),
                        ],
                        default="prompt",
                        max_length=20,
                        verbose_name="Тип стратегии",
                    ),
                ),
                (
                    "strategy_options",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Опции стратегии"
                    ),
                ),
                (
                    "source_urls",
                    models.TextField(
                        blank=True, verbose_name="URL источников (по одному на строке)"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Теги (через запятую)"
                    ),
                ),
                (
                    "posting_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("biweekly", "Раз в две недели"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Частота публикаций",
                    ),
                ),
                (
                    "articles_per_run",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Статей за раз",
                    ),
                ),
                (
                    "min_word_count",
                    models.IntegerField(
                        default=1000,
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Минимум слов в статье",
                    ),
                ),
                (
                    "max_word_count",
                    models.IntegerField(
                        default=1500,
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Максимум слов в статье",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, verbose_name="Ключевые фразы для включения"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        default="дружелюбный и экспертный",
                        max_length=200,
                        verbose_name="Тон статьи",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний запуск"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Следующий запуск"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "video_sources_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Использовать видеоисточники"
                    ),
                ),
                (
                    "video_platforms",
                    models.JSONField(
                        default=list, verbose_name="Видеоплатформы для парсинга"
                    ),
                ),
                (
                    "auto_publish_to_platforms",
                    models.JSONField(
                        default=list, verbose_name="Автопубликация анонсов"
                    ),
                ),
                (
                    "video_embed_in_articles",
                    models.BooleanField(
                        default=False, verbose_name="Встраивать видео в статьи"
                    ),
                ),
                (
                    "telegram_channels",
                    models.JSONField(default=list, verbose_name="Telegram каналы"),
                ),
                (
                    "rutube_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Публиковать на Rutube"
                    ),
                ),
                (
                    "dzen_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Публиковать в Дзен"
                    ),
                ),
                (
                    "vk_enabled",
                    models.BooleanField(default=False, verbose_name="Публиковать в VK"),
                ),
                (
                    "style_strength",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Сила имитации стиля",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Точное время запуска"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("generate_article", "Генерация статей"),
                            ("add_likes", "Лайки (случайные статьи)"),
                            ("add_comments", "Комментарии (случайные статьи)"),
                        ],
                        default="generate_article",
                        max_length=50,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "static_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Статические параметры"
                    ),
                ),
                (
                    "dynamic_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Динамические параметры"
                    ),
                ),
                (
                    "max_runs",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Максимум запусков"
                    ),
                ),
                (
                    "current_run_count",
                    models.IntegerField(
                        default=0, verbose_name="Текущий счётчик запусков"
                    ),
                ),
                (
                    "payload_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON-данные, которые будут переданы в пайплайн при запуске",
                        verbose_name="Payload для пайплайна",
                    ),
                ),
                (
                    "schedule_kind",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно в указанное время"),
                            ("weekly", "Раз в неделю"),
                            ("interval", "Через каждые N минут"),
                            ("cron", "По cron-выражению"),
                        ],
                        default="daily",
                        max_length=16,
                        verbose_name="Тип расписания",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Используется, если выбран тип "По cron-выражению"',
                        max_length=120,
                        verbose_name="CRON выражение",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Интервал, минут",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        null=True,
                        verbose_name="День недели (для еженедельных запусков)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="Категория для публикации",
                    ),
                ),
                (
                    "mimic_author_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mimicked_by_ai",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Писать в стиле автора",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="Asistent.prompttemplate",
                        verbose_name="Шаблон промпта",
                    ),
                ),
            ],
            options={
                "verbose_name": "📋 Задания: Расписание AI",
                "verbose_name_plural": "📋 Задания: Расписания AI",
                "db_table": "Asistent_aischedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Промпт-шаблон"),
                            ("system", "Системная задача"),
                            ("manual", "Ручной режим"),
                            ("pipeline", "Пайплайн автоматизации"),
                        ],
                        max_length=20,
                        verbose_name="Стратегия",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("partial", "Частично"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, verbose_name="Создано объектов"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Ошибки"),
                ),
                (
                    "context_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="Контекст"),
                ),
                (
                    "result_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результат"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="schedule.aischedule",
                        verbose_name="Расписание",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI расписание: запуск",
                "verbose_name_plural": "AI расписание: запуски",
                "db_table": "Asistent_aischedulerun",
                "ordering": ["-started_at"],
            },
        ),
    ]
