# Generated by Django 5.1 on 2025-10-21 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0023_urlredirect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='@ideal_image_ru или числовой ID', max_length=200, verbose_name='ID канала')),
                ('channel_name', models.CharField(max_length=200, verbose_name='Название канала')),
                ('channel_type', models.CharField(choices=[('beauty', 'Красота'), ('fashion', 'Мода'), ('health', 'Здоровье'), ('lifestyle', 'Образ жизни'), ('psychology', 'Психология'), ('kids', 'Дети'), ('family', 'Семья'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип канала')),
                ('channel_url', models.URLField(blank=True, verbose_name='URL канала')),
                ('subscribers_count', models.IntegerField(default=0, verbose_name='Количество подписчиков')),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Процент активных подписчиков', verbose_name='Вовлечённость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для автопостинга')),
                ('posting_rules', models.JSONField(blank=True, default=dict, help_text='Частота, категории, время', verbose_name='Правила постинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '📢 Соцсети: Канал',
                'verbose_name_plural': '📢 Соцсети: Каналы',
                'ordering': ['platform', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('pinterest', 'Pinterest'), ('rutube', 'Rutube'), ('dzen', 'Яндекс.Дзен'), ('whatsapp', 'WhatsApp'), ('max', 'MAX'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=50, unique=True, verbose_name='Платформа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('api_credentials', models.JSONField(blank=True, default=dict, help_text='JSON с токенами и ключами', verbose_name='API учётные данные')),
                ('rate_limits', models.JSONField(blank=True, default=dict, help_text='Ограничения на количество запросов', verbose_name='Лимиты API')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('requires_vpn', models.BooleanField(default=False, help_text='Для Instagram, Facebook, YouTube', verbose_name='Требуется VPN')),
                ('icon_class', models.CharField(blank=True, help_text='Например: fab fa-telegram', max_length=100, verbose_name='CSS класс иконки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '📱 Соцсети: Платформа',
                'verbose_name_plural': '📱 Соцсети: Платформы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('platform_post_id', models.CharField(blank=True, max_length=200, verbose_name='ID поста в соцсети')),
                ('platform_url', models.URLField(blank=True, verbose_name='URL поста')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('publishing', 'Публикуется'), ('published', 'Опубликовано'), ('failed', 'Ошибка'), ('deleted', 'Удалено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Репосты')),
                ('engagement_score', models.FloatField(default=0.0, verbose_name='Показатель вовлечённости')),
                ('post_content', models.TextField(blank=True, help_text='Адаптированный контент для платформы', verbose_name='Текст публикации')),
                ('error_log', models.TextField(blank=True, verbose_name='Логи ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publications', to='blog.post', verbose_name='Статья')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='Sozseti.socialchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': '📊 Соцсети: Публикация',
                'verbose_name_plural': '📊 Соцсети: Публикации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название расписания')),
                ('posting_frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('3times_day', '3 раза в день'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=20, verbose_name='Частота публикаций')),
                ('optimal_times', models.JSONField(default=list, help_text='Список часов [10, 14, 19]', verbose_name='Оптимальные часы')),
                ('content_template', models.TextField(blank=True, help_text='Используйте {title}, {url}, {description}', verbose_name='Шаблон поста')),
                ('hashtags', models.CharField(blank=True, help_text='Через пробел: #красота #мода', max_length=500, verbose_name='Хештеги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('ai_optimization', models.BooleanField(default=False, help_text='AI определяет лучшее время', verbose_name='AI оптимизация времени')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(blank=True, help_text='Какие категории постить', related_name='social_schedules', to='blog.category', verbose_name='Категории статей')),
                ('channels', models.ManyToManyField(related_name='schedules', to='Sozseti.socialchannel', verbose_name='Каналы')),
            ],
            options={
                'verbose_name': '📅 Соцсети: Расписание',
                'verbose_name_plural': '📅 Соцсети: Расписания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossPostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('conditions', models.JSONField(default=dict, help_text='Когда применять: min_views, categories', verbose_name='Условия')),
                ('transform_content', models.BooleanField(default=False, help_text='Адаптировать под целевую платформу', verbose_name='Трансформировать контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosspost_source', to='Sozseti.socialchannel', verbose_name='Исходный канал')),
                ('target_channels', models.ManyToManyField(related_name='crosspost_target', to='Sozseti.socialchannel', verbose_name='Целевые каналы')),
            ],
            options={
                'verbose_name': '🔄 Соцсети: Правило кросс-постинга',
                'verbose_name_plural': '🔄 Соцсети: Правила кросс-постинга',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('subscribers_gained', models.IntegerField(default=0, verbose_name='Прирост подписчиков')),
                ('subscribers_lost', models.IntegerField(default=0, verbose_name='Отток подписчиков')),
                ('posts_published', models.IntegerField(default=0, verbose_name='Опубликовано постов')),
                ('total_views', models.IntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_engagement', models.IntegerField(default=0, verbose_name='Всего взаимодействий')),
                ('ai_insights', models.JSONField(default=dict, verbose_name='Рекомендации AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('top_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_analytics', to='Sozseti.postpublication', verbose_name='Топ пост дня')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Sozseti.socialchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': '📈 Соцсети: Аналитика канала',
                'verbose_name_plural': '📈 Соцсети: Аналитика каналов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=200, verbose_name='ID комментария')),
                ('author_id', models.CharField(max_length=200, verbose_name='ID автора')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерирован')),
                ('ai_reply', models.TextField(blank=True, verbose_name='Ответ AI')),
                ('sentiment', models.CharField(choices=[('positive', 'Позитивный'), ('neutral', 'Нейтральный'), ('negative', 'Негативный')], default='neutral', max_length=20, verbose_name='Тональность')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Sozseti.postpublication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': '💬 Соцсети: Комментарий',
                'verbose_name_plural': '💬 Соцсети: Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='ID пользователя')),
                ('user_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('message_thread', models.JSONField(default=list, verbose_name='История сообщений')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('archived', 'В архиве'), ('spam', 'Спам')], default='active', max_length=20, verbose_name='Статус')),
                ('ai_responded', models.BooleanField(default=False, verbose_name='AI ответил')),
                ('needs_admin', models.BooleanField(default=False, verbose_name='Требуется админ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='Sozseti.socialchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': '💬 Соцсети: Переписка',
                'verbose_name_plural': '💬 Соцсети: Переписка',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='socialchannel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='Sozseti.socialplatform', verbose_name='Платформа'),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Бюджет (руб.)')),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Потрачено (руб.)')),
                ('target_audience', models.JSONField(default=dict, help_text='Таргетинг: возраст, пол, интересы', verbose_name='Целевая аудитория')),
                ('ad_content', models.TextField(verbose_name='Контент рекламы')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('metrics', models.JSONField(default=dict, help_text='Показы, клики, конверсии', verbose_name='Метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('platforms', models.ManyToManyField(related_name='ad_campaigns', to='Sozseti.socialplatform', verbose_name='Платформы')),
            ],
            options={
                'verbose_name': '💰 Соцсети: Рекламная кампания',
                'verbose_name_plural': '💰 Соцсети: Рекламные кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Основные, Тематические, Экспериментальные', max_length=200, verbose_name='Название группы')),
                ('posting_strategy', models.CharField(choices=[('all', 'Во все каналы'), ('random', 'Случайный выбор'), ('by_type', 'По типу контента'), ('best_performing', 'В лучшие по метрикам')], default='by_type', max_length=50, verbose_name='Стратегия распределения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('channels', models.ManyToManyField(limit_choices_to={'platform__name': 'telegram'}, related_name='telegram_groups', to='Sozseti.socialchannel', verbose_name='Каналы')),
            ],
            options={
                'verbose_name': '📱 Telegram: Группа каналов',
                'verbose_name_plural': '📱 Telegram: Группы каналов',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='postpublication',
            index=models.Index(fields=['post', 'channel'], name='Sozseti_pos_post_id_1510ee_idx'),
        ),
        migrations.AddIndex(
            model_name='postpublication',
            index=models.Index(fields=['status', '-created_at'], name='Sozseti_pos_status_acabe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelanalytics',
            unique_together={('channel', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='socialchannel',
            unique_together={('platform', 'channel_id')},
        ),
    ]
