# Generated by Django 5.0.8 on 2025-12-03 11:01

from django.db import migrations


def copy_chatbot_data(apps, schema_editor):
    """Копирование данных из старых таблиц Asistent в новые ChatBot_AI"""
    
    db_alias = schema_editor.connection.alias
    
    # Используем прямые SQL запросы для копирования данных между таблицами
    with schema_editor.connection.cursor() as cursor:
        # Проверяем существование старых таблиц
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'Asistent_chatbotsettings'
        """)
        
        if cursor.fetchone()[0] > 0:
            # Копируем настройки чат-бота
            cursor.execute("""
                INSERT IGNORE INTO ChatBot_AI_chatbotsettings 
                    (id, system_prompt, welcome_message, use_ai, search_articles, 
                     max_search_results, admin_contact_enabled, admin_email, 
                     rate_limit_messages, is_active, updated_at)
                SELECT 
                    id, system_prompt, welcome_message, use_ai, search_articles,
                    max_search_results, admin_contact_enabled, admin_email,
                    rate_limit_messages, is_active, updated_at
                FROM Asistent_chatbotsettings
            """)
            
            # Копируем FAQ
            cursor.execute("""
                INSERT IGNORE INTO ChatBot_AI_chatbotfaq
                    (id, question, answer, keywords, related_url, priority, 
                     is_active, usage_count, embedding, created_at, updated_at)
                SELECT 
                    id, question, answer, keywords, related_url, priority,
                    is_active, usage_count, embedding, created_at, updated_at
                FROM Asistent_chatbotfaq
            """)
            
            # Копируем историю сообщений
            cursor.execute("""
                INSERT IGNORE INTO ChatBot_AI_chatmessage
                    (id, session_key, user_id, message, response, source,
                     found_articles, processing_time, ip_address, user_agent, created_at)
                SELECT 
                    id, session_key, user_id, message, response, source,
                    found_articles, processing_time, ip_address, user_agent, created_at
                FROM Asistent_chatmessage
            """)
            
            print("✅ Данные чат-бота скопированы из Asistent в ChatBot_AI")
        else:
            print("ℹ️ Старые таблицы Asistent не найдены, пропускаем копирование")


def reverse_copy(apps, schema_editor):
    """Откат - очистка новых таблиц"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM ChatBot_AI_chatmessage")
        cursor.execute("DELETE FROM ChatBot_AI_chatbotfaq")
        cursor.execute("DELETE FROM ChatBot_AI_chatbotsettings")
        print("↩️ Данные ChatBot_AI очищены (откат миграции)")


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot_AI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_chatbot_data, reverse_copy),
    ]
