# Generated by Django 5.0.8 on 2025-12-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0029_add_og_preview_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории или тематики для парсинга (например: "Мода", "Красота", "Здоровье")', max_length=200, verbose_name='Название категории')),
                ('search_queries', models.JSONField(default=list, help_text='Список поисковых запросов для поиска статей (JSON массив строк)', verbose_name='Поисковые запросы')),
                ('sources', models.JSONField(default=list, help_text='Список источников для парсинга: ["google", "yandex", "rss", "social"]', verbose_name='Источники')),
                ('is_active', models.BooleanField(default=True, help_text='Включена ли эта категория для парсинга', verbose_name='Активна')),
                ('articles_per_day', models.IntegerField(default=5, help_text='Количество статей для парсинга в день по этой категории', verbose_name='Статей в день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('site_category', models.ForeignKey(blank=True, help_text='В какую категорию сайта распределять спаршенные статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_categories', to='blog.category', verbose_name='Категория сайта')),
            ],
            options={
                'verbose_name': '📰 Категория парсинга',
                'verbose_name_plural': '📰 Категории парсинга',
                'db_table': 'asistent_parsingcategory',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParsedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Спаршенный текст статьи (~200 слов)', verbose_name='Содержание')),
                ('source_url', models.URLField(max_length=1000, verbose_name='URL источника')),
                ('source_name', models.CharField(help_text='Название сайта или источника (например: "vc.ru", "Yandex")', max_length=200, verbose_name='Название источника')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='pending', max_length=20, verbose_name='Статус')),
                ('selected_for_posting', models.BooleanField(default=False, help_text='Отмечена модератором для автопостинга', verbose_name='Выбрана для публикации')),
                ('popularity_score', models.IntegerField(default=0, help_text='Оценка популярности статьи (лайки, просмотры и т.д.)', verbose_name='Популярность')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки модератора', verbose_name='Заметки')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_articles', to='blog.category', verbose_name='Категория сайта')),
                ('published_article', models.ForeignKey(blank=True, help_text='Ссылка на опубликованную статью на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_source', to='blog.post', verbose_name='Опубликованная статья')),
                ('parsing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_articles', to='Parsers.parsingcategory', verbose_name='Категория парсинга')),
            ],
            options={
                'verbose_name': '📄 Спаршенная статья',
                'verbose_name_plural': '📄 Спаршенные статьи',
                'db_table': 'asistent_parsedarticle',
                'ordering': ['-parsed_at', '-popularity_score'],
                'indexes': [models.Index(fields=['-parsed_at'], name='asistent_pa_parsed__1285ea_idx'), models.Index(fields=['status'], name='asistent_pa_status_19a791_idx'), models.Index(fields=['selected_for_posting'], name='asistent_pa_selecte_6a7932_idx'), models.Index(fields=['category', '-parsed_at'], name='asistent_pa_categor_029ed4_idx')],
            },
        ),
    ]
