# Generated by Django 5.0.8 on 2024-09-11 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время регистрации на сайте'),
            preserve_default=False,
        ),
    ]
