# Generated by Django 5.0.8 on 2024-10-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0003_profile_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('vizitor',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='profile',
                    name='vizitor',
                    field=models.OneToOneField(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=models.CASCADE,
                        related_name='profile'
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='profile',
            name='spez',
            field=models.CharField(blank=True, max_length=80, verbose_name='cпециальность'),
        ),
        migrations.CreateModel(
            name='Pisaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekvisit', models.CharField(blank=True, max_length=80, verbose_name='реквизиты к оплате')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('prais', models.IntegerField(blank=True, verbose_name='расценка')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='Характеристика')),
                ('psevdonim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Писатель',
                'verbose_name_plural': 'Писатели',
                'db_table': 'app_pisaka',
                'ordering': ['psevdonim'],
            },
        ),
    ]
