# Generated by Django 5.2.7 on 2025-10-09 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0005_add_tasks_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('vizitor',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('article_created', 'Создана статья'), ('article_liked', 'Лайк статьи'), ('article_viewed', 'Просмотр статьи'), ('comment_added', 'Добавлен комментарий'), ('donation_received', 'Получен донат'), ('user_registered', 'Регистрация пользователя'), ('role_applied', 'Подана заявка на роль'), ('role_granted', 'Получена роль'), ('subscription_added', 'Новая подписка')], max_length=50, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed_tasks_count',
            field=models.IntegerField(default=0, verbose_name='Выполнено заданий AI'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации на сайте'),
        ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='spez',
        #     field=models.CharField(blank=True, max_length=80, verbose_name='cпециальность'),
        # ),  # ОТКЛЮЧЕНО: поле уже существует, AlterField вызывает конфликты при миграции на MySQL
        migrations.AlterField(
            model_name='profile',
            name='vizitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roleapplication',
            name='role',
            field=models.CharField(choices=[('author', 'Автор'), ('moderator', 'Модератор'), ('marketer', 'Маркетолог')], max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронный адрес (email)')),
                ('content', models.TextField(verbose_name='Содержимое письма')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'app_feedback',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Pisaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekvisit', models.CharField(blank=True, max_length=80, verbose_name='реквизиты к оплате')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('prais', models.IntegerField(blank=True, verbose_name='расценка')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='Характеристика')),
                ('psevdonim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pisakas', to=settings.AUTH_USER_MODEL, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Писатель',
                'verbose_name_plural': 'Писатели',
                'db_table': 'app_pisaka',
                'ordering': ['psevdonim'],
            },
        ),
    ]
