# Generated by Django 5.1 on 2025-10-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0006_alter_profile_options_alter_activitylog_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ОТКЛЮЧЕНО: поле 'user' уже переименовано в 'vizitor' в миграции 0001_initial
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Уникальный идентификатор сессии пользователя', max_length=255, unique=True, verbose_name='Ключ сессии')),
                ('necessary', models.BooleanField(default=True, help_text='Необходимы для работы сайта', verbose_name='Обязательные cookies')),
                ('functional', models.BooleanField(default=False, help_text='Улучшают функциональность сайта', verbose_name='Функциональные cookies')),
                ('analytics', models.BooleanField(default=False, help_text='Для анализа посещаемости', verbose_name='Аналитические cookies')),
                ('advertising', models.BooleanField(default=False, help_text='Для показа персонализированной рекламы', verbose_name='Рекламные cookies')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, help_text='Браузер и ОС пользователя', verbose_name='User Agent')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата согласия')),
                ('user', models.ForeignKey(blank=True, help_text='Если пользователь авторизован', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Согласие на Cookie',
                'verbose_name_plural': 'Согласия на Cookie',
                'db_table': 'app_cookie_consent',
                'ordering': ['-consent_date'],
            },
        ),
    ]
