# Generated by Django 5.1 on 2025-10-20 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Visitor", "0002_update_profile"),
        ("Visitor", "0004_alter_profile_options_rename_user_profile_vizitor_and_more"),
        ("Visitor", "0007_remove_profile_user_cookieconsent"),
    ]

    operations = []
