# Generated by Django 5.1 on 2025-10-20 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Visitor", "0008_merge_20251020_1415"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pisaka",
            name="psevdonim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pisakas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Псевдоним",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="spez",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="cпециальность"
            ),
        ),
    ]
