# Generated by Django 5.0.1 on 2026-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0009_alter_pisaka_psevdonim_alter_profile_spez'),
    ]

    operations = [
        # Добавляем / меняем колонку prais безопасно (даже если её нет в БД)
        migrations.RunSQL(
            sql="""
                SET @col_exists = (
                    SELECT COUNT(*) FROM information_schema.COLUMNS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'app_pisaka'
                    AND COLUMN_NAME = 'prais'
                );
                SET @sql = IF(@col_exists > 0,
                    'ALTER TABLE app_pisaka MODIFY COLUMN prais INT NULL',
                    'ALTER TABLE app_pisaka ADD COLUMN prais INT NULL'
                );
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            # state_operations сообщает Django об изменении модели (чтобы не создавались новые миграции)
            state_operations=[
                migrations.AlterField(
                    model_name='pisaka',
                    name='prais',
                    field=models.IntegerField(blank=True, null=True, verbose_name='расценка'),
                ),
            ],
        ),
    ]
